// AP Exam Practice — subject registry
// Metadata only. Question banks live in data/<id>.js and are loaded separately.
//
// FIELDS
//   tier            1 = text/image MCQ, fully buildable now.
//                   2 = MCQ section depends on audio (listening/aural) which this
//                       framework doesn't play back yet.
//   releaseStatus   "draft"    = never selectable on the catalog, even if its bank
//                                has questions in it. This is the default and the
//                                only safe state for work-in-progress content.
//                   "released" = selectable, provided the bank also has questions.
//                   Gating on this field (instead of bank length alone) is what
//                   stops a single WIP question from silently publishing a subject.
//   formatVerified  true  = mcqCount / mcqTimeMinutes / totalExamTimeLabel were
//                           checked against College Board's published exam page
//                           during the pass noted in the inline comment.
//                   false = inherited from an older draft; the catalog card says so.
//   allowsMultiSelect  Whether this subject's MCQ section actually uses
//                      "select two/three" items. Currently false everywhere: no AP
//                      MCQ section in the current exam cycle uses multi-select
//                      (AP Physics 1/2 were the last holdouts and dropped them in
//                      the 2024-25 redesign). Enforced by tests/schema tests so a
//                      bank can't quietly grow multi-select items.
//   units           Optional unit/category metadata. For weighted subjects,
//                   examWeight is the point estimate used by the drawer and
//                   examWeightRange is College Board's published [min, max] band.
//                   Set-blueprint subjects may use id/name only as result labels.
//
// Format verification pass: 2026-08-09, against apstudents.collegeboard.org
// "About the Exam" pages (the 2026 administration) unless noted otherwise.
const AP_SUBJECTS = [
  {
    id: "ap-art-history",
    name: "AP Art History",
    category: "Arts",
    tier: 1,
    // VERIFIED 2026-08-13 against current AP Central course and exam pages.
    // Section I: 80 MCQs in 60 minutes, 50% of score; 2-3 question image sets
    // plus individual questions using works both within and beyond the prescribed image set.
    mcqCount: 80,
    mcqTimeMinutes: 60,
    totalExamTimeLabel: "3h 0m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: false,
    tierNote: "Includes image-based question sets and unfamiliar-work visual analysis; use View larger image when you need to inspect detail.",
    units: [
      { id:"U1", name:"Global Prehistory, 30,000–500 BCE", examWeight:0.04, examWeightRange:[0.04,0.04] },
      { id:"U2", name:"Ancient Mediterranean, 3500 BCE–300 CE", examWeight:0.15, examWeightRange:[0.15,0.15] },
      { id:"U3", name:"Early Europe and Colonial Americas, 200–1750 CE", examWeight:0.21, examWeightRange:[0.21,0.21] },
      { id:"U4", name:"Later Europe and Americas, 1750–1980 CE", examWeight:0.21, examWeightRange:[0.21,0.21] },
      { id:"U5", name:"Indigenous Americas, 1000 BCE–1980 CE", examWeight:0.06, examWeightRange:[0.06,0.06] },
      { id:"U6", name:"Africa, 1100–1980 CE", examWeight:0.06, examWeightRange:[0.06,0.06] },
      { id:"U7", name:"West and Central Asia, 500 BCE–1980 CE", examWeight:0.04, examWeightRange:[0.04,0.04] },
      { id:"U8", name:"South, East, and Southeast Asia, 300 BCE–1980 CE", examWeight:0.08, examWeightRange:[0.08,0.08] },
      { id:"U9", name:"The Pacific, 700–1980 CE", examWeight:0.04, examWeightRange:[0.04,0.04] },
      { id:"U10", name:"Global Contemporary, 1980 CE to Present", examWeight:0.11, examWeightRange:[0.11,0.11] },
    ],
    skillCountRanges: { "1":[12,15], "2":[23,25], "3":[9,10], "4":[16,20], "5":[5,6], "6":[5,6], "7":[5,6] },
    stimulusSetRange: [20,20],
    // Exact constructive draw: 15 prescribed-work image sets + 5 unfamiliar-work
    // image sets = 40 visual questions. Standalones then produce an exact skill
    // mix of 15/24/10/16/5/5/5 while preserving Hamilton unit counts
    // 3/12/17/17/5/5/3/6/3/9.
    artHistoryBlueprint: { perUnit: {
      U1:  { knownSets:1, unknownSets:0, standalone:{ "4":1 } },
      U2:  { knownSets:2, unknownSets:1, standalone:{ "2":1, "3":2, "4":2, "7":1 } },
      U3:  { knownSets:3, unknownSets:1, standalone:{ "2":2, "3":2, "4":4, "7":1 } },
      U4:  { knownSets:3, unknownSets:3, standalone:{ "2":1, "3":1, "4":2, "7":1 } },
      U5:  { knownSets:1, unknownSets:0, standalone:{ "3":1, "4":1, "7":1 } },
      U6:  { knownSets:1, unknownSets:0, standalone:{ "2":1, "3":1, "4":1 } },
      U7:  { knownSets:1, unknownSets:0, standalone:{ "3":1 } },
      U8:  { knownSets:1, unknownSets:0, standalone:{ "2":1, "3":1, "4":2 } },
      U9:  { knownSets:1, unknownSets:0, standalone:{ "2":1 } },
      U10: { knownSets:1, unknownSets:0, standalone:{ "2":2, "3":1, "4":3, "7":1 } },
    } },
    dataVar: "QUESTIONS_AP_ART_HISTORY",
  },
  {
    id: "ap-music-theory",
    name: "AP Music Theory",
    category: "Arts",
    tier: 2,
    mcqCount: 75,
    mcqTimeMinutes: 65,
    totalExamTimeLabel: "2h 5m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes aural/sight-singing questions — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_MUSIC_THEORY",
  },
  {
    id: "ap-english-language",
    name: "AP English Language and Composition",
    category: "English",
    tier: 1,
    mcqCount: 45,
    mcqTimeMinutes: 60,
    totalExamTimeLabel: "3h 15m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    tierNote: null,
    units: [
      { id: "READING", name: "Reading Questions", examWeight: 24 / 45, examWeightRange: [24 / 45, 24 / 45] },
      { id: "WRITING", name: "Writing Questions", examWeight: 21 / 45, examWeightRange: [21 / 45, 21 / 45] },
    ],
    setBlueprint: {
      setCount: 5,
      totalQuestions: 45,
      unitCounts: { READING: 24, WRITING: 21 },
    },
    dataVar: "QUESTIONS_AP_ENGLISH_LANGUAGE",
  },
  {
    id: "ap-english-literature",
    name: "AP English Literature and Composition",
    category: "English",
    tier: 1,
    mcqCount: 55,
    mcqTimeMinutes: 60,
    totalExamTimeLabel: "3h 0m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    tierNote: null,
    units: [
      { id: "PROSE", name: "Prose Fiction", examWeight: 0.455, examWeightRange: [0.42, 0.49] },
      { id: "POETRY", name: "Poetry", examWeight: 0.405, examWeightRange: [0.36, 0.45] },
      { id: "DRAMA", name: "Drama / Longer Fiction", examWeight: 0.16, examWeightRange: [0.15, 0.18] },
    ],
    setBlueprint: { setCount: 5, totalQuestions: 55 },
    dataVar: "QUESTIONS_AP_ENGLISH_LITERATURE",
  },
  {
    id: "ap-african-american-studies",
    name: "AP African American Studies",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 60,
    mcqTimeMinutes: 70,
    totalExamTimeLabel: "2h 50m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_AFRICAN_AMERICAN_STUDIES",
  },
  {
    id: "ap-comparative-government",
    name: "AP Comparative Government and Politics",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 55,
    mcqTimeMinutes: 60,
    totalExamTimeLabel: "2h 30m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_COMPARATIVE_GOVERNMENT",
  },
  {
    id: "ap-european-history",
    name: "AP European History",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 55,
    mcqTimeMinutes: 55,
    totalExamTimeLabel: "3h 15m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_EUROPEAN_HISTORY",
  },
  {
    id: "ap-human-geography",
    name: "AP Human Geography",
    category: "History & Social Sciences",
    tier: 1,
    // VERIFIED 2026-08-13 against current AP Central course, CED, and exam pages.
    mcqCount: 60,
    mcqTimeMinutes: 60,
    totalExamTimeLabel: "2h 15m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: false,
    tierNote: null,
    units: [
      { id: "U1", name: "Thinking Geographically", examWeight: 0.09, examWeightRange: [0.08, 0.10] },
      { id: "U2", name: "Population and Migration Patterns and Processes", examWeight: 0.145, examWeightRange: [0.12, 0.17] },
      { id: "U3", name: "Cultural Patterns and Processes", examWeight: 0.145, examWeightRange: [0.12, 0.17] },
      { id: "U4", name: "Political Patterns and Processes", examWeight: 0.145, examWeightRange: [0.12, 0.17] },
      { id: "U5", name: "Agriculture and Rural Land-Use Patterns and Processes", examWeight: 0.145, examWeightRange: [0.12, 0.17] },
      { id: "U6", name: "Cities and Urban Land-Use Patterns and Processes", examWeight: 0.145, examWeightRange: [0.12, 0.17] },
      { id: "U7", name: "Industrial and Economic Development Patterns and Processes", examWeight: 0.145, examWeightRange: [0.12, 0.17] },
    ],
    examBlueprint: { sets: { quantitative: 4, foundational: 0, text: 0, visual: 3 }, standaloneRange: [39, 39] },
    skillCountRanges: { "1": [15, 21], "2": [10, 15], "3": [8, 12], "4": [8, 12], "5": [8, 12] },
    dataVar: "QUESTIONS_AP_HUMAN_GEOGRAPHY",
  },
  {
    id: "ap-macroeconomics",
    name: "AP Macroeconomics",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 60,
    mcqTimeMinutes: 70,
    totalExamTimeLabel: "2h 10m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_MACROECONOMICS",
  },
  {
    id: "ap-microeconomics",
    name: "AP Microeconomics",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 60,
    mcqTimeMinutes: 70,
    totalExamTimeLabel: "2h 10m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_MICROECONOMICS",
  },
  {
    id: "ap-psychology",
    name: "AP Psychology",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 75,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "2h 40m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_PSYCHOLOGY",
  },
  {
    id: "ap-us-government",
    name: "AP United States Government and Politics",
    category: "History & Social Sciences",
    tier: 1,
    // VERIFIED 2026-08-09: apstudents.collegeboard.org/courses/ap-united-states-government-and-politics/assessment
    // — Section I: Multiple Choice, 55 questions, 1hr 20mins, 50% of score; total duration 3hrs.
    // MCQ section is a mix of individual questions and question sets built on data,
    // foundational-document excerpts, and other text/visual sources.
    mcqCount: 55,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "3h 0m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    tierNote: null,
    // Unit exam weightings from the AP U.S. Government and Politics CED
    // (Course Framework V.1, © 2026 College Board, p. "Exam Weighting"), verified
    // 2026-08-09 against the CED PDF on AP Central. examWeight is the midpoint of
    // the published band and is what the Hamilton apportionment drawer uses;
    // examWeightRange is the published band the draw audit asserts against.
    units: [
      { id: "U1", name: "Foundations of American Democracy", examWeight: 0.185, examWeightRange: [0.15, 0.22] },
      { id: "U2", name: "Interactions Among Branches of Government", examWeight: 0.305, examWeightRange: [0.25, 0.36] },
      { id: "U3", name: "Civil Liberties and Civil Rights", examWeight: 0.155, examWeightRange: [0.13, 0.18] },
      { id: "U4", name: "American Political Ideologies and Beliefs", examWeight: 0.125, examWeightRange: [0.10, 0.15] },
      { id: "U5", name: "Political Participation", examWeight: 0.235, examWeightRange: [0.20, 0.27] },
    ],
    // Effective Fall 2026 CED, p. 169: five quantitative sets, two text sets
    // (one foundational document and one other source), and three visual sets.
    // The selected stimulus groups vary between two and three questions, so the
    // achievable leftover standalone count currently ranges from 28 to 32.
    // Recompute this range whenever the Government stimulus pools change.
    examBlueprint: {
      sets: { quantitative: 5, foundational: 1, text: 1, visual: 3 },
      standaloneRange: [28, 32],
    },
    dataVar: "QUESTIONS_AP_US_GOVERNMENT",
  },
  {
    id: "ap-us-history",
    name: "AP United States History",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 55,
    mcqTimeMinutes: 55,
    totalExamTimeLabel: "3h 15m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_US_HISTORY",
  },
  {
    id: "ap-world-history",
    name: "AP World History: Modern",
    category: "History & Social Sciences",
    tier: 1,
    mcqCount: 55,
    mcqTimeMinutes: 55,
    totalExamTimeLabel: "3h 15m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_WORLD_HISTORY",
  },
  {
    id: "ap-calculus-ab",
    name: "AP Calculus AB",
    category: "Math & Computer Science",
    tier: 1,
    // VERIFIED 2026-08-10 against the official AP Calculus AB and BC Course
    // and Exam Description PDF (apcentral.collegeboard.org/media/pdf/
    // ap-calculus-ab-and-bc-course-and-exam-description.pdf), "Exam Overview"
    // and "Exam Weighting for the Multiple-Choice Section" tables — NOT
    // reconstructed from secondary sources. Section I: 42 multiple-choice
    // questions, 100 minutes total, split into two timed parts (see
    // examParts below): Part A, 29 questions/62 minutes/no calculator, and
    // Part B, 13 questions/38 minutes/calculator required. A prior pass of
    // this file cited these same 29/13/100 totals but only enforced the
    // 29/13 *count* split (attributeRanges) without ever separating the two
    // parts into distinct timed sections in the delivered exam — see
    // examParts and js/draw.js's orderByExamParts.
    mcqCount: 42,
    mcqTimeMinutes: 100,
    totalExamTimeLabel: "3h 15m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: true,
    tierNote: null,
    units: [
      { id: "U1", name: "Limits and Continuity", examWeight: 0.12, examWeightRange: [0.10, 0.12] },
      { id: "U2", name: "Differentiation: Definition and Fundamental Properties", examWeight: 0.12, examWeightRange: [0.10, 0.12] },
      { id: "U3", name: "Differentiation: Composite, Implicit, and Inverse Functions", examWeight: 0.12, examWeightRange: [0.10, 0.12] },
      { id: "U4", name: "Contextual Applications of Differentiation", examWeight: 0.12, examWeightRange: [0.10, 0.15] },
      { id: "U5", name: "Analytical Applications of Differentiation", examWeight: 0.16, examWeightRange: [0.15, 0.18] },
      { id: "U6", name: "Integration and Accumulation of Change", examWeight: 0.20, examWeightRange: [0.17, 0.20] },
      { id: "U7", name: "Differential Equations", examWeight: 0.09, examWeightRange: [0.06, 0.12] },
      { id: "U8", name: "Applications of Integration", examWeight: 0.13, examWeightRange: [0.10, 0.15] },
    ],
    sciencePracticeRanges: { "1": [7, 11], "2": [4, 7], "3": [7, 11], "4": [4, 7], "5": [7, 11] },
    attributeRanges: { calculatorAllowed: { false: [29, 29], true: [13, 13] } },
    examParts: {
      field: "calculatorAllowed",
      parts: [
        { value: false, label: "Part A — Calculator not permitted", timeMinutes: 62 },
        { value: true, label: "Part B — Graphing calculator required", timeMinutes: 38 },
      ],
    },
    dataVar: "QUESTIONS_AP_CALCULUS_AB",
  },
  {
    id: "ap-calculus-bc",
    name: "AP Calculus BC",
    category: "Math & Computer Science",
    tier: 1,
    mcqCount: 42,
    mcqTimeMinutes: 100,
    totalExamTimeLabel: "3h 15m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_CALCULUS_BC",
  },
  {
    id: "ap-computer-science-a",
    name: "AP Computer Science A",
    category: "Math & Computer Science",
    tier: 1,
    mcqCount: 42,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "3h 0m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_COMPUTER_SCIENCE_A",
  },
  {
    id: "ap-computer-science-principles",
    name: "AP Computer Science Principles",
    category: "Math & Computer Science",
    tier: 1,
    mcqCount: 70,
    mcqTimeMinutes: 120,
    totalExamTimeLabel: "2h 0m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "MCQ is the entire exam-day test; the Create Performance Task is separate coursework, not modeled here.",
    units: [],
    dataVar: "QUESTIONS_AP_COMPUTER_SCIENCE_PRINCIPLES",
  },
  {
    id: "ap-precalculus",
    name: "AP Precalculus",
    category: "Math & Computer Science",
    tier: 1,
    // VERIFIED 2026-08-13 against AP Central and the Fall 2026 CED clarifications.
    // Effective May 2027, Section I has 42 MCQs in 105 minutes: Part A has
    // 29 questions / 65 minutes with no calculator; Part B has 13 questions /
    // 40 minutes with a graphing calculator required. Section II has four FRQs
    // in 70 minutes. This site currently practices Section I only.
    mcqCount: 42,
    mcqTimeMinutes: 105,
    totalExamTimeLabel: "2h 55m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    tierNote: null,
    // AP Central 2026-27 course page: Units 1-3 are assessed; Unit 4 is not.
    // Published MCQ bands are U1 30-40%, U2 25-40%, U3 30-35%.
    // Midpoint weights normalized to one yield the 15/14/13 integer blueprint.
    units: [
      { id: "U1", name: "Polynomial and Rational Functions", examWeight: 0.35, examWeightRange: [0.30, 0.40] },
      { id: "U2", name: "Exponential and Logarithmic Functions", examWeight: 0.325, examWeightRange: [0.25, 0.40] },
      { id: "U3", name: "Trigonometric and Polar Functions", examWeight: 0.325, examWeightRange: [0.30, 0.35] },
    ],
    examParts: {
      field: "calculatorAllowed",
      parts: [
        { value: false, label: "Part A — Calculator not permitted", timeMinutes: 65 },
        { value: true, label: "Part B — Graphing calculator required", timeMinutes: 40 },
      ],
    },
    attributeRanges: {
      calculatorAllowed: { false: [29, 29], true: [13, 13] },
    },
    freeResponse: {
      timeMinutes: 70,
      questions: [
        "Question 1 (Function Concepts)",
        "Question 2 (Modeling a Non-Periodic Context)",
        "Question 3 (Modeling a Periodic Context)",
        "Question 4 (Symbolic Manipulations)",
      ],
    },
    dataVar: "QUESTIONS_AP_PRECALCULUS",
  },
  {
    id: "ap-statistics",
    name: "AP Statistics",
    category: "Math & Computer Science",
    tier: 1,
    // VERIFIED 2026-08-11 against the AP Statistics CED, Effective Fall 2026:
    // https://apcentral.collegeboard.org/media/pdf/ap-statistics-course-and-exam-description.pdf
    // and the AP Statistics revisions page for the May 2027 redesign. Section I has
    // 42 four-option MCQs in 90 minutes, including one 3-question probability set and
    // one 3-question regression set; calculators are permitted throughout.
    // College Board publishes unit bands, not exact counts. Midpoints are 25/20/20/15/15
    // (sum 95); normalizing those midpoints to 42 questions and applying Hamilton
    // apportionment gives 11/9/9/7/6, with the U4/U5 remainder tie resolved by unit order.
    mcqCount: 42,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "3h 0m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: true,
    tierNote: "Effective May 2027 five-unit exam redesign.",
    units: [
      { id: "U1", name: "Exploring Data", examWeight: 0.25, examWeightRange: [0.20, 0.30] },
      { id: "U2", name: "Collecting Data", examWeight: 0.20, examWeightRange: [0.15, 0.25] },
      { id: "U3", name: "Probability, Random Variables, and Probability Distributions", examWeight: 0.20, examWeightRange: [0.15, 0.25] },
      { id: "U4", name: "Inference for Proportions", examWeight: 0.15, examWeightRange: [0.10, 0.20] },
      { id: "U5", name: "Inference for Means", examWeight: 0.15, examWeightRange: [0.10, 0.20] },
    ],
    skillCountRanges: { "1": [10, 15], "2": [6, 12], "3": [10, 15], "4": [6, 12] },
    requiredSetBlueprint: { probability: 1, regression: 1 },
    dataVar: "QUESTIONS_AP_STATISTICS",
  },
  {
    id: "ap-biology",
    name: "AP Biology",
    category: "Sciences",
    tier: 1,
    mcqCount: 60,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "3h 0m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: true,
    tierNote: null,
    units: [
      { id: "U1", name: "Chemistry of Life", examWeight: 0.105, examWeightRange: [0.08, 0.13] },
      { id: "U2", name: "Cell Structure and Function", examWeight: 0.105, examWeightRange: [0.10, 0.13] },
      { id: "U3", name: "Cellular Energetics", examWeight: 0.145, examWeightRange: [0.12, 0.16] },
      { id: "U4", name: "Cell Communication and Cell Cycle", examWeight: 0.125, examWeightRange: [0.10, 0.15] },
      { id: "U5", name: "Heredity", examWeight: 0.09, examWeightRange: [0.08, 0.11] },
      { id: "U6", name: "Gene Expression and Regulation", examWeight: 0.145, examWeightRange: [0.12, 0.16] },
      { id: "U7", name: "Natural Selection", examWeight: 0.145, examWeightRange: [0.13, 0.20] },
      { id: "U8", name: "Ecology", examWeight: 0.145, examWeightRange: [0.10, 0.15] },
    ],
    sciencePracticeRanges: { "1": [7, 11], "2": [4, 7], "3": [7, 11], "4": [4, 7], "5": [7, 11], "6": [4, 7] },
    stimulusSetRange: [6, 10],
    dataVar: "QUESTIONS_AP_BIOLOGY",
  },
  {
    id: "ap-chemistry",
    name: "AP Chemistry",
    category: "Sciences",
    tier: 1,
    mcqCount: 60,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "3h 15m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: true,
    tierNote: null,
    units: [
      { id: "U1", name: "Atomic Structure and Properties", examWeight: 0.075, examWeightRange: [0.07, 0.09] },
      { id: "U2", name: "Compound Structure and Properties", examWeight: 0.19, examWeightRange: [0.18, 0.22] },
      { id: "U3", name: "Properties of Substances and Mixtures", examWeight: 0.20, examWeightRange: [0.18, 0.22] },
      { id: "U4", name: "Chemical Reactions", examWeight: 0.075, examWeightRange: [0.07, 0.09] },
      { id: "U5", name: "Kinetics", examWeight: 0.075, examWeightRange: [0.07, 0.09] },
      { id: "U6", name: "Thermochemistry", examWeight: 0.075, examWeightRange: [0.07, 0.09] },
      { id: "U7", name: "Equilibrium", examWeight: 0.075, examWeightRange: [0.07, 0.09] },
      { id: "U8", name: "Acids and Bases", examWeight: 0.13, examWeightRange: [0.11, 0.15] },
      { id: "U9", name: "Thermodynamics and Electrochemistry", examWeight: 0.115, examWeightRange: [0.11, 0.15] },
    ],
    sciencePracticeRanges: { "1": [7, 11], "2": [4, 7], "3": [7, 11], "4": [4, 7], "5": [7, 11], "6": [4, 7] },
    stimulusSetRange: [6, 10],
    dataVar: "QUESTIONS_AP_CHEMISTRY",
  },
  {
    id: "ap-environmental-science",
    name: "AP Environmental Science",
    category: "Sciences",
    tier: 1,
    mcqCount: 80,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "2h 40m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_ENVIRONMENTAL_SCIENCE",
  },
  {
    id: "ap-physics-1",
    name: "AP Physics 1",
    category: "Sciences",
    tier: 1,
    mcqCount: 40,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "3h 0m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_PHYSICS_1",
  },
  {
    id: "ap-physics-2",
    name: "AP Physics 2",
    category: "Sciences",
    tier: 1,
    // VERIFIED 2026-08-10 against official AP Physics CED and AP Central assessment page.
    mcqCount: 42,
    mcqTimeMinutes: 90,
    totalExamTimeLabel: "3h 0m",
    formatVerified: true,
    releaseStatus: "released",
    allowsMultiSelect: false,
    calculatorAllowed: true,
    tierNote: null,
    units: [
      { id: "U9", name: "Thermodynamics", examWeight: 0.12, examWeightRange: [0.12, 0.12] },
      { id: "U10", name: "Electric Force, Field, and Potential", examWeight: 0.18, examWeightRange: [0.18, 0.18] },
      { id: "U11", name: "Electric Circuits", examWeight: 0.18, examWeightRange: [0.18, 0.18] },
      { id: "U12", name: "Magnetism and Electromagnetism", examWeight: 0.15, examWeightRange: [0.15, 0.15] },
      { id: "U13", name: "Geometric Optics", examWeight: 0.12, examWeightRange: [0.12, 0.12] },
      { id: "U14", name: "Waves, Sound, and Physical Optics", examWeight: 0.12, examWeightRange: [0.12, 0.12] },
      { id: "U15", name: "Modern Physics", examWeight: 0.13, examWeightRange: [0.13, 0.13] },
    ],
    sciencePracticeRanges: { "1": [7, 11], "2": [4, 7], "3": [7, 11], "4": [4, 7], "5": [7, 11], "6": [4, 7] },
    stimulusSetRange: [6, 10],
    dataVar: "QUESTIONS_AP_PHYSICS_2",
  },
  {
    id: "ap-physics-c-mechanics",
    name: "AP Physics C: Mechanics",
    category: "Sciences",
    tier: 1,
    mcqCount: 40,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "3h 0m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_PHYSICS_C_MECHANICS",
  },
  {
    id: "ap-physics-c-em",
    name: "AP Physics C: Electricity and Magnetism",
    category: "Sciences",
    tier: 1,
    mcqCount: 40,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "3h 0m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_PHYSICS_C_EM",
  },
  {
    id: "ap-chinese",
    name: "AP Chinese Language and Culture",
    category: "World Languages & Cultures",
    tier: 2,
    mcqCount: 70,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "2h 15m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes listening/speaking sections — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_CHINESE",
  },
  {
    id: "ap-french",
    name: "AP French Language and Culture",
    category: "World Languages & Cultures",
    tier: 2,
    mcqCount: 65,
    mcqTimeMinutes: 95,
    totalExamTimeLabel: "3h 3m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes listening/speaking sections — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_FRENCH",
  },
  {
    id: "ap-german",
    name: "AP German Language and Culture",
    category: "World Languages & Cultures",
    tier: 2,
    mcqCount: 65,
    mcqTimeMinutes: 95,
    totalExamTimeLabel: "3h 3m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes listening/speaking sections — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_GERMAN",
  },
  {
    id: "ap-italian",
    name: "AP Italian Language and Culture",
    category: "World Languages & Cultures",
    tier: 2,
    mcqCount: 65,
    mcqTimeMinutes: 95,
    totalExamTimeLabel: "3h 3m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes listening/speaking sections — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_ITALIAN",
  },
  {
    id: "ap-japanese",
    name: "AP Japanese Language and Culture",
    category: "World Languages & Cultures",
    tier: 2,
    mcqCount: 70,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "2h 15m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes listening/speaking sections — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_JAPANESE",
  },
  {
    id: "ap-spanish-language",
    name: "AP Spanish Language and Culture",
    category: "World Languages & Cultures",
    tier: 2,
    mcqCount: 65,
    mcqTimeMinutes: 95,
    totalExamTimeLabel: "3h 3m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: "Includes listening/speaking sections — audio playback not yet supported.",
    units: [],
    dataVar: "QUESTIONS_AP_SPANISH_LANGUAGE",
  },
  {
    id: "ap-spanish-literature",
    name: "AP Spanish Literature and Culture",
    category: "World Languages & Cultures",
    tier: 1,
    mcqCount: 65,
    mcqTimeMinutes: 80,
    totalExamTimeLabel: "3h 0m",
    formatVerified: false,
    releaseStatus: "draft",
    allowsMultiSelect: false,
    tierNote: null,
    units: [],
    dataVar: "QUESTIONS_AP_SPANISH_LITERATURE",
  },
];

const AP_CATEGORIES = [
  "Arts",
  "English",
  "History & Social Sciences",
  "Math & Computer Science",
  "Sciences",
  "World Languages & Cultures",
];

if (typeof module !== "undefined") {
  module.exports = { AP_SUBJECTS, AP_CATEGORIES };
}
