const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const subject=require('./helpers/ap-environmental-science-candidate');
const catalog=fs.readFileSync('js/catalog.js','utf8');
const about=fs.readFileSync('about.html','utf8');
test('APES naive student preflight exposes the May 2027 exam-critical facts',()=>{
 assert.equal(subject.releaseStatus,'draft');
 assert.equal(subject.formatVerified,true);
 assert.equal(subject.mcqCount,80);
 assert.equal(subject.mcqTimeMinutes,90);
 assert.equal(subject.totalExamTimeLabel,'2h 40m');
 assert.equal(subject.calculatorAllowed,true);
 assert.equal(subject.freeResponse.timeMinutes,70);
 assert.equal(subject.freeResponse.questions.length,3);
 assert.match(subject.tierNote,/calculator/i);
 assert.match(catalog,/saved in this browser session/);
 assert.match(catalog,/timer starts only after you choose Start timed practice/i);
 assert.match(catalog,/Back to subjects/);
 assert.match(about,/currently an MCQ-only practice site/i);
 assert.match(about,/does not provide free-response questions/i);
});
