from pathlib import Path
p=Path('data/ap-physics-c-em.js')
s=p.read_text()
marker='window.QUESTIONS_AP_PHYSICS_C_EM = E;'
chunk=r'''
add("em-8.4-01","U8","8.4","Electric Fields of Charge Distributions","2.A","A thin rod lies along the x-axis from x=0 to x=L with uniform linear charge density λ. For an observation point at x=a>L, which differential expression gives the field contribution from an element dx?","dE = kλ dx/(a−x)² in the +x direction","dE = kλ dx/(a−x) in the +x direction","dE = kλ(a−x) dx in the +x direction","dE = kλ dx/(a²+x²) in the +x direction","The charge element is dq=λdx and its distance from the observation point is a−x, so Coulomb's law gives k dq/(a−x)² directed away from the positive element along +x.");
add("em-8.4-02","U8","8.4","Electric Fields of Charge Distributions","3.B","At the exact center of a uniformly charged circular ring, the electric field is zero because","fields from diametrically opposite charge elements cancel vectorially","each charge element produces zero electric field at the center","the ring contains equal positive and negative charge","electric field cannot exist inside a charged object","Every charge element has a diametrically opposite element at the same distance producing an equal field in the opposite direction, so the vector sum vanishes by symmetry.");
add("em-8.4-03","U8","8.4","Electric Fields of Charge Distributions","2.C","Two uniformly charged rings have equal total charge but different radii. At the exact center of each ring, how do their electric-field magnitudes compare?","They are equal and both zero","The smaller ring has the larger field","The larger ring has the larger field","The comparison depends on the sign of the charge","Circular symmetry cancels contributions from opposite elements at the center of either uniformly charged ring, so both net electric fields are exactly zero regardless of radius.");
add("em-8.4-04","U8","8.4","Electric Fields of Charge Distributions","2.D","Far from a localized charge distribution with nonzero total charge Q, increasing the observation distance by a factor of 3 changes the leading electric-field magnitude by approximately","a factor of 1/9","a factor of 1/3","a factor of 3","a factor of 9","At distances much larger than the distribution size, its leading field is the monopole field of total charge Q, so E scales as 1/r² and falls to one ninth when r triples.");
add("em-8.5-01","U8","8.5","Electric Flux","2.B","A uniform electric field of 200 N/C passes through a flat area of 0.30 m². The field makes a 60° angle with the area vector. What is the electric flux?","30 N·m²/C","60 N·m²/C","52 N·m²/C","120 N·m²/C","Electric flux through a flat surface is Φ=EA cosθ=(200)(0.30)cos60°=30 N·m²/C, with θ measured from the surface's area vector.");
add("em-8.5-02","U8","8.5","Electric Flux","2.C","The same uniform electric field passes through two equal flat surfaces. Surface A has its area vector parallel to the field; surface B has its area vector perpendicular to the field. Compared with A, the flux through B is","zero","the same","half as large","twice as large","Flux is EA cosθ. A parallel area vector has θ=0 and maximum flux, whereas a perpendicular area vector has θ=90° and therefore zero flux.");
add("em-8.5-03","U8","8.5","Electric Flux","3.B","A closed surface encloses no net charge but has several external point charges nearby. Which statement about the total electric flux through the surface is correct?","The net flux is zero even though the field can be nonzero on the surface","The net flux must be positive because field lines enter the surface","The net flux depends on the surface area","The net flux equals the external charge magnitude divided by ε₀","Gauss's law relates total closed-surface flux only to enclosed net charge. External charges can create local fields, but their entering and leaving flux contributions sum to zero.");
add("em-8.5-04","U8","8.5","Electric Flux","2.D","For fixed uniform electric-field magnitude and fixed flat area, rotating the area vector from 0° to 60° relative to the field changes the flux by what factor?","1/2","√3/2","2","4","With E and A fixed, flux scales as cosθ; changing from cos0°=1 to cos60°=1/2 reduces the electric flux to one half of its original value.");
add("em-8.6-01","U8","8.6","Gauss's Law","2.B","A spherical Gaussian surface encloses a point charge +4.0 nC. What is the net electric flux through the surface?","4.52×10² N·m²/C","2.26×10² N·m²/C","9.04×10² N·m²/C","4.52×10⁻² N·m²/C","Gauss's law gives Φ=Qenc/ε₀=4.0×10⁻⁹/(8.85×10⁻¹²)≈4.52×10² N·m²/C, independent of sphere radius or the charge's position inside.");
add("em-8.6-02","U8","8.6","Gauss's Law","2.A","A uniformly charged solid sphere has radius R and total charge Q. For r<R, which expression gives the electric-field magnitude?","E = Qr/(4πε₀R³)","E = Q/(4πε₀r²)","E = Qr²/(4πε₀R⁴)","E = QR/(4πε₀r³)","Uniform volume charge gives Qenc=Q(r³/R³). Substitution into E(4πr²)=Qenc/ε₀ yields E=Qr/(4πε₀R³), so the interior field grows linearly with r.");
add("em-8.6-03","U8","8.6","Gauss's Law","3.C","A student chooses a cubic Gaussian surface around a point charge at its center and says Gauss's law cannot be used because the field is not constant over each face. Which response is best?","Gauss's law still fixes total flux, although the cube does not make the field easy to extract from the integral","Gauss's law is valid only for spherical or cylindrical surfaces","The cube gives zero net flux because opposite faces cancel","The law fails whenever electric field is not perpendicular to a surface","Gauss's law applies to every closed surface, but symmetry is needed to pull E outside the flux integral; a cube therefore gives correct total flux without directly yielding a simple E value.");
add("em-8.6-04","U8","8.6","Gauss's Law","2.C","A point charge q is first centered inside a spherical Gaussian surface and then moved off center while remaining inside. How does the total electric flux through the sphere change?","It does not change","It increases","It decreases","It becomes zero","The enclosed charge remains q in both cases, so Gauss's law fixes the same total flux q/ε₀ even though moving the charge changes how flux is distributed over the surface.");
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,chunk+'\n'+marker))
