from pathlib import Path
p=Path('data/ap-physics-c-em.js'); s=p.read_text(); marker='window.QUESTIONS_AP_PHYSICS_C_EM = E;'
chunk=r'''
add("em-10.1-01","U10","10.1","Electrostatics with Conductors","3.B","A solid conductor is in electrostatic equilibrium with no current flowing through it. Which statement about the electric field inside the conducting material is correct?","The electric field is zero","The field points toward the conductor's center","The field is uniform but nonzero","The field equals the surface charge density divided by ε₀ throughout the material","If a nonzero electric field existed inside the conducting material, mobile charges would accelerate and the conductor would not be in electrostatic equilibrium; therefore the interior field must be zero.");
add("em-10.1-02","U10","10.1","Electrostatics with Conductors","3.C","A charged conductor in electrostatic equilibrium has excess charge on its surface. Which reasoning best justifies this result?","Excess charge in the conducting bulk would create an internal field that drives charge until equilibrium is restored","Charge is pulled to the surface by gravity","The conductor's center cannot contain electric potential","Surface charge appears because the electric field outside every conductor is zero","Electrostatic equilibrium requires zero electric field within the conducting material; mobile excess charge therefore redistributes until no bulk field remains, leaving net excess charge on the surface.");
add("em-10.1-03","U10","10.1","Electrostatics with Conductors","2.B","The electric field immediately outside a conducting surface in vacuum is 3.0×10⁴ N/C and is normal to the surface. What is the local surface charge density?","2.66×10⁻⁷ C/m²","3.39×10¹⁵ C/m²","8.85×10⁻¹² C/m²","3.0×10⁴ C/m²","Immediately outside a conductor, E=σ/ε₀. Thus σ=ε₀E=(8.85×10⁻¹²)(3.0×10⁴)≈2.66×10⁻⁷ C/m², with sign set by the outward field direction.");
add("em-10.1-04","U10","10.1","Electrostatics with Conductors","2.C","Two points lie within the material of the same conductor in electrostatic equilibrium. Compared with one another, their electric potentials are","equal","larger at the point closer to the surface","smaller at the point closer to the surface","equal only if the conductor is spherical","Because the electric field inside the conducting material is zero and E=−∇V, the potential has no spatial gradient there; the entire connected conductor is an equipotential.");
add("em-10.2-01","U10","10.2","Redistribution of Charge between Conductors","3.B","Two well-separated conducting spheres of different radii are connected by a thin conducting wire and allowed to reach electrostatic equilibrium. Which quantity must be equal for the two spheres?","Electric potential","Surface electric field","Surface charge density","Total charge","Connected conductors exchange charge until there is no potential difference to drive further motion, so their electric potentials become equal even though their charges and surface fields can differ.");
add("em-10.2-02","U10","10.2","Redistribution of Charge between Conductors","2.A","Two well-separated conducting spheres of radii R and 2R are connected and carry total charge Q. Neglecting mutual influence, which charges satisfy equal potential and charge conservation?","Q/3 on the R sphere and 2Q/3 on the 2R sphere","Q/2 on each sphere","2Q/3 on the R sphere and Q/3 on the 2R sphere","Q/5 on the R sphere and 4Q/5 on the 2R sphere","For an isolated sphere V=kq/R. Equal potential gives q₁/R=q₂/(2R), so q₂=2q₁; together with q₁+q₂=Q this yields q₁=Q/3 and q₂=2Q/3.");
add("em-10.2-03","U10","10.2","Redistribution of Charge between Conductors","2.C","For two connected spheres of radii R and 2R at equal potential, how do their surface electric-field magnitudes compare after equilibrium?","The smaller sphere's surface field is twice the larger sphere's","The larger sphere's surface field is twice the smaller sphere's","The surface fields are equal","The smaller sphere's surface field is four times the larger sphere's","At equal potential q is proportional to R. Since a sphere's surface field is kq/R², E is proportional to 1/R; therefore the radius-R sphere has twice the surface field of the radius-2R sphere.");
add("em-10.2-04","U10","10.2","Redistribution of Charge between Conductors","2.D","Two isolated spherical conductors differ only in radius, with one having twice the radius. If each is raised to the same electric potential relative to infinity, how do their stored charges compare?","The larger sphere stores twice as much charge","The larger sphere stores four times as much charge","They store the same charge","The larger sphere stores half as much charge","An isolated sphere has capacitance C=4πε₀R and Q=CV. At fixed V, charge is proportional to radius, so doubling R doubles the charge required to reach the same potential.");
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,chunk+'\n'+marker))
