from pathlib import Path
p=Path('data/ap-physics-c-em.js'); s=p.read_text(); marker='window.QUESTIONS_AP_PHYSICS_C_EM = E;'
chunk=r'''
add("em-10.3-01","U10","10.3","Capacitors","2.B","A capacitor stores 6.0 μC when the potential difference across it is 12 V. What is its capacitance?","0.50 μF","2.0 μF","72 μF","0.072 μF","Capacitance is C=Q/ΔV, so C=(6.0 μC)/(12 V)=0.50 μF. The result depends on capacitor geometry and dielectric, not on the particular stored charge alone.");
add("em-10.3-02","U10","10.3","Capacitors","2.A","Ignoring fringing, which expression gives the capacitance of a vacuum parallel-plate capacitor with plate area A and separation d?","C = ε₀A/d","C = ε₀d/A","C = A/(ε₀d)","C = ε₀Ad","For oppositely charged parallel plates, E=σ/ε₀ and ΔV=Ed=Qd/(ε₀A). Substituting into C=Q/ΔV gives C=ε₀A/d.");
add("em-10.3-03","U10","10.3","Capacitors","2.B","A 4.0 μF capacitor is charged to 10 V. How much energy is stored in its electric field?","2.0×10⁻⁴ J","4.0×10⁻⁴ J","2.0×10⁻⁵ J","4.0×10⁻⁵ J","Capacitor energy is U=½CV²=½(4.0×10⁻⁶ F)(10 V)²=2.0×10⁻⁴ J, representing energy stored in the electric field between the conductors.");
add("em-10.3-04","U10","10.3","Capacitors","2.D","For an isolated parallel-plate capacitor with fixed charge, the plate separation is doubled while area is unchanged. By what factor does the stored electric energy change?","It doubles","It halves","It quadruples","It remains unchanged","For fixed charge U=Q²/(2C), while C=ε₀A/d. Doubling d halves capacitance, so stored energy doubles because mechanical work is done separating the attracting plates.");
add("em-10.4-01","U10","10.4","Dielectrics","3.B","A dielectric slab completely fills a parallel-plate capacitor while the capacitor remains connected to an ideal battery. Which statement is correct after insertion?","Capacitance and stored charge increase while voltage remains fixed","Capacitance increases while stored charge remains fixed","Voltage increases while capacitance remains fixed","Stored charge decreases while voltage remains fixed","The dielectric increases capacitance by the factor κ. The ideal battery holds the potential difference fixed, so Q=CV increases as additional charge flows from the battery onto the plates.");
add("em-10.4-02","U10","10.4","Dielectrics","3.C","A charged capacitor is disconnected from its battery before a dielectric is inserted fully between its plates. Why does the voltage decrease?","The free charge remains fixed while the dielectric increases capacitance, so V=Q/C decreases","The dielectric removes free charge from the plates","The dielectric decreases capacitance and therefore lowers voltage","The battery absorbs electric potential from the capacitor","Once disconnected, no conducting path exists for free plate charge to change. Polarization increases capacitance by κ, and with Q fixed the relation V=Q/C requires potential difference to fall.");
add("em-10.4-03","U10","10.4","Dielectrics","2.A","A dielectric of relative permittivity κ completely fills the gap of a parallel-plate capacitor of area A and separation d. Which expression gives its capacitance?","C = κε₀A/d","C = ε₀A/(κd)","C = κε₀d/A","C = ε₀A/d","A linear dielectric reduces the internal field for a given free charge by polarization, increasing capacitance by factor κ relative to vacuum; therefore C=κε₀A/d.");
add("em-10.4-04","U10","10.4","Dielectrics","2.D","A capacitor remains connected to a fixed-voltage battery while a dielectric with κ=3 is inserted fully. By what factor does the stored electric energy change?","It increases by a factor of 3","It decreases by a factor of 3","It increases by a factor of 9","It remains unchanged","At fixed battery voltage U=½CV². Full dielectric insertion multiplies capacitance by κ=3 while V remains fixed, so stored energy increases by the same factor of 3.");
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,chunk+'\n'+marker))
