from pathlib import Path
p=Path('data/ap-physics-c-em.js')
s=p.read_text()
marker='window.QUESTIONS_AP_PHYSICS_C_EM = E;'
chunk=r'''
add("em-9.1-01","U9","9.1","Electric Potential Energy","2.B","Two point charges +2.0 μC and +3.0 μC are separated by 0.40 m. What is their electric potential energy relative to infinite separation?","0.135 J","−0.135 J","0.0674 J","0.270 J","For two point charges, U=kq₁q₂/r=(8.99×10⁹)(6.0×10⁻¹²)/0.40≈+0.135 J; like charges have positive interaction energy relative to infinity.");
add("em-9.1-02","U9","9.1","Electric Potential Energy","2.D","If the separation between two fixed like point charges is doubled, their electric potential energy becomes","one half as large","one fourth as large","twice as large","unchanged","The point-charge interaction energy U=kq₁q₂/r is inversely proportional to separation, so doubling r reduces U by a factor of two while preserving its positive sign.");
add("em-9.1-03","U9","9.1","Electric Potential Energy","3.B","A negative charge is moved quasistatically closer to a fixed positive charge. Which statement is correct?","The system's electric potential energy decreases","The system's electric potential energy increases","The system's potential energy remains zero","The potential-energy change depends on the path taken","For opposite charges U=kq₁q₂/r is negative; decreasing r makes U more negative, so the system's potential energy decreases independent of path because electrostatic force is conservative.");
add("em-9.1-04","U9","9.1","Electric Potential Energy","2.A","Which expression gives the electric potential energy of three point charges q₁, q₂, and q₃ separated pairwise by distances r₁₂, r₁₃, and r₂₃?","k(q₁q₂/r₁₂ + q₁q₃/r₁₃ + q₂q₃/r₂₃)","k(q₁q₂q₃)/(r₁₂r₁₃r₂₃)","k(q₁+q₂+q₃)/(r₁₂+r₁₃+r₂₃)","k(q₁q₂/r₁₂² + q₁q₃/r₁₃² + q₂q₃/r₂₃²)","Electrostatic potential energy is the sum over distinct interacting charge pairs, with each pair contributing kqᵢqⱼ/rᵢⱼ exactly once rather than using an inverse-square dependence.");
add("em-9.2-01","U9","9.2","Electric Potential","2.B","What electric potential is produced by a +5.0 nC point charge at a distance of 0.20 m, taking zero potential at infinity?","225 V","112 V","450 V","22.5 V","For a point charge, V=kQ/r=(8.99×10⁹)(5.0×10⁻⁹)/0.20≈225 V; potential is a scalar and retains the sign of the source charge.");
add("em-9.2-02","U9","9.2","Electric Potential","2.C","At a point equidistant from charges +Q and −Q, the electric potential is zero. Which statement about the electric field there is necessarily true?","The electric field need not be zero","The electric field must also be zero","The electric field is undefined","The electric field can be zero only if Q=0","Potential adds as a scalar and equal opposite contributions can cancel, while electric field is a vector whose contributions can reinforce; zero potential therefore does not imply zero field.");
add("em-9.2-03","U9","9.2","Electric Potential","2.A","For a one-dimensional electrostatic potential V(x), which relationship gives the x-component of electric field?","Eₓ = −dV/dx","Eₓ = dV/dx","Eₓ = −V/x","Eₓ = ∫V dx","Electric field is the negative spatial gradient of electric potential, so in one dimension Eₓ=−dV/dx; the minus sign points the field toward decreasing potential.");
add("em-9.2-04","U9","9.2","Electric Potential","3.C","A graph of V versus x has a constant positive slope over a region. Which claim about the electric field in that region is best justified?","The field is uniform and points in the negative x-direction","The field is uniform and points in the positive x-direction","The field increases linearly in the positive x-direction","The field is zero because the potential is linear","Because Eₓ=−dV/dx, a constant positive potential slope corresponds to a constant negative electric field, so the field is uniform and directed toward decreasing x.");
add("em-9.3-01","U9","9.3","Conservation of Electric Energy","2.B","A proton moves from a point at 120 V to a point at 20 V. What is the change in its electric potential energy?","−100 eV","+100 eV","−140 eV","+140 eV","For charge +e, ΔU=qΔV=e(20−120)V=−100 eV; the proton loses electric potential energy as it moves to lower electric potential.");
add("em-9.3-02","U9","9.3","Conservation of Electric Energy","3.B","An electron is released from rest in an electrostatic field and moves to a region of higher electric potential. Neglecting other forces, what happens to its kinetic energy?","It increases","It decreases","It remains constant","It must first decrease and then increase","For an electron q<0, moving to higher V makes U=qV decrease. Conservation of mechanical energy therefore requires kinetic energy to increase by the same amount.");
add("em-9.3-03","U9","9.3","Conservation of Electric Energy","2.A","A particle of charge q and mass m starts from rest and moves through a potential difference such that its electric potential energy decreases by magnitude |qΔV|. Which expression gives its final speed?","√(2|qΔV|/m)","|qΔV|/m","√(|qΔV|/2m)","2|qΔV|/m","Energy conservation gives ΔK=−ΔU=|qΔV|. With Kf=½mv² from rest, solving ½mv²=|qΔV| yields v=√(2|qΔV|/m).");
add("em-9.3-04","U9","9.3","Conservation of Electric Energy","2.C","Two particles with equal mass and charge magnitudes +q and −q are each released from rest through potential changes chosen so that each loses the same electric potential energy. Their final speeds are","equal","larger for +q","larger for −q","not comparable without knowing the path shape","If each particle loses the same amount of electric potential energy, energy conservation gives each the same kinetic-energy gain; equal masses therefore lead to equal final speeds.");
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,chunk+'\n'+marker))
