from pathlib import Path
bp=Path('data/ap-physics-c-mechanics.js')
b=bp.read_text()
marker='  window.QUESTIONS_AP_PHYSICS_C_MECHANICS = QUESTIONS;\n'
if marker not in b: raise SystemExit('bank export marker not found')
block=r'''
  // Original three-question data sets. Each stimulus is shared by reference.
  const PCM_SET_U1 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"A motion sensor records the horizontal position of a cart at equal one-second intervals while the cart moves along a straight track.", columns:["t (s)","x (m)"], rows:[[0,0],[1,1],[2,4],[3,9],[4,16]] };
  p("pcm-set-u1-01","U1","1.2","Displacement, Velocity, and Acceleration","2.A","Which position function is consistent with the table?",["x=t","x=t^2","x=2t","x=4t"],1,"The listed positions are the squares of the corresponding times: 0, 1, 4, 9, and 16. Therefore x=t^2 fits every data point.",{stimulusGroupId:"pcm-set-u1",stimulus:PCM_SET_U1});
  p("pcm-set-u1-02","U1","1.2","Displacement, Velocity, and Acceleration","2.B","Using the model supported by the table, what is the cart's instantaneous velocity at t=3 s?",["3 m/s","6 m/s","9 m/s","12 m/s"],1,"From the data x=t^2, so v=dx/dt=2t. At t=3 s the instantaneous velocity is 6 m/s.",{stimulusGroupId:"pcm-set-u1",stimulus:PCM_SET_U1});
  p("pcm-set-u1-03","U1","1.3","Representing Motion","3.C","Which claim about the motion is supported by the successive position changes in the table?",["The cart moves at constant speed","The cart has positive acceleration","The cart has negative velocity","The cart returns toward the origin"],1,"During successive one-second intervals the position changes are 1, 3, 5, and 7 m. Increasing interval displacements show increasing velocity and therefore positive acceleration.",{stimulusGroupId:"pcm-set-u1",stimulus:PCM_SET_U1});

  const PCM_SET_U2 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"A student pulls a cart in a horizontal circle of fixed radius and records the cart speed and measured inward net force for several trials.", columns:["v (m/s)","F inward (N)"], rows:[[1,2],[2,8],[3,18],[4,32]] };
  p("pcm-set-u2-01","U2","2.10","Circular Motion","3.C","Which functional relationship is supported by the data?",["F is proportional to v","F is proportional to v^2","F is proportional to 1/v","F is independent of v"],1,"The ratio F/v^2 is 2 N s^2/m^2 for every row, so the measured inward force is proportional to the square of speed.",{stimulusGroupId:"pcm-set-u2",stimulus:PCM_SET_U2});
  p("pcm-set-u2-02","U2","2.10","Circular Motion","2.D","If the cart speed were 5 m/s under otherwise identical conditions, what force would the model predict?",["10 N","25 N","50 N","64 N"],2,"The table gives F=2v^2. At 5 m/s, the predicted inward force is 2(25)=50 N.",{stimulusGroupId:"pcm-set-u2",stimulus:PCM_SET_U2});
  p("pcm-set-u2-03","U2","2.10","Circular Motion","2.A","For fixed mass and radius, which theoretical expression has the dependence observed in the table?",["F=mv/r","F=mv^2/r","F=mr/v","F=mv^2 r"],1,"Uniform circular motion requires F_in=mv^2/r. With mass and radius fixed, this expression predicts exactly the observed v-squared dependence.",{stimulusGroupId:"pcm-set-u2",stimulus:PCM_SET_U2});

  const PCM_SET_U3 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"A force sensor measures a one-dimensional force on a cart at several positions; between listed points the force varies linearly with position.", columns:["x (m)","F (N)"], rows:[[0,0],[1,2],[2,4],[3,6]] };
  p("pcm-set-u3-01","U3","3.2","Work","2.B","How much work does the force do from x=0 to x=3 m?",["6 J","9 J","12 J","18 J"],1,"The force-position graph is a straight line from 0 N to 6 N, so the area underneath is a triangle: (1/2)(3 m)(6 N)=9 J.",{stimulusGroupId:"pcm-set-u3",stimulus:PCM_SET_U3});
  p("pcm-set-u3-02","U3","3.2","Work","2.A","Which force function matches the data?",["F=x","F=2x","F=x^2","F=2/x"],1,"Every row has force equal to twice the position coordinate, so the linear force law F(x)=2x reproduces all measurements.",{stimulusGroupId:"pcm-set-u3",stimulus:PCM_SET_U3});
  p("pcm-set-u3-03","U3","3.4","Conservation of Energy","3.B","If this is the only force on a cart initially at rest at x=0, what does the positive work through x=3 m imply?",["Kinetic energy decreases by 9 J","Kinetic energy increases by 9 J","Potential energy and kinetic energy both stay zero","Momentum must remain zero"],1,"By the work-energy theorem, net work equals the change in kinetic energy. The 9 J of positive work therefore raises the cart's kinetic energy by 9 J.",{stimulusGroupId:"pcm-set-u3",stimulus:PCM_SET_U3});

  const PCM_SET_U4 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"A force probe records the horizontal force on a cart during a short collision; force changes linearly between the listed times.", columns:["t (s)","F (N)"], rows:[[0,0],[0.1,20],[0.2,20],[0.3,0]] };
  p("pcm-set-u4-01","U4","4.2","Change in Momentum and Impulse","2.B","What impulse is delivered to the cart from 0 to 0.3 s?",["2 N s","4 N s","6 N s","20 N s"],1,"The force-time area is two triangles of 1 N s each plus a rectangle of 2 N s, for a total impulse of 4 N s.",{stimulusGroupId:"pcm-set-u4",stimulus:PCM_SET_U4});
  p("pcm-set-u4-02","U4","4.2","Change in Momentum and Impulse","3.C","Which feature of the data directly determines the cart's momentum change?",["The peak force alone","The area under the force-time curve","The final force alone","The slope only during the middle interval"],1,"The impulse-momentum theorem states Delta p=integral F dt, so the area under the force-time curve determines the momentum change.",{stimulusGroupId:"pcm-set-u4",stimulus:PCM_SET_U4});
  p("pcm-set-u4-03","U4","4.2","Change in Momentum and Impulse","2.D","If the same force-time curve were stretched to twice the duration without changing force values, how would the impulse change?",["It would halve","It would double","It would quadruple","It would remain unchanged"],1,"Stretching every time interval by a factor of two doubles the horizontal scale and therefore doubles the total area under the force-time curve and its impulse.",{stimulusGroupId:"pcm-set-u4",stimulus:PCM_SET_U4});

  const PCM_SET_U5 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"A rigid rotor is tested with several applied net torques while its angular acceleration is measured about the same fixed axis.", columns:["tau (N m)","alpha (rad/s^2)"], rows:[[2,1],[4,2],[6,3],[8,4]] };
  p("pcm-set-u5-01","U5","5.6","Newton's Second Law in Rotational Form","2.B","What rotational inertia is implied by the data?",["0.5 kg m^2","2 kg m^2","4 kg m^2","8 kg m^2"],1,"For each row tau/alpha=2 kg m^2. Since tau=I alpha, the rotor's rotational inertia is 2 kg m^2.",{stimulusGroupId:"pcm-set-u5",stimulus:PCM_SET_U5});
  p("pcm-set-u5-02","U5","5.6","Newton's Second Law in Rotational Form","3.C","Which observation supports treating the rotational inertia as constant?",["Torque is always positive","The ratio tau/alpha is constant","Angular acceleration is nonzero","The largest torque occurs last"],1,"A constant value of tau/alpha across all trials means the proportionality constant I in tau=I alpha remains unchanged.",{stimulusGroupId:"pcm-set-u5",stimulus:PCM_SET_U5});
  p("pcm-set-u5-03","U5","5.6","Newton's Second Law in Rotational Form","2.D","What angular acceleration would a 10 N m net torque produce for the same rotor?",["2 rad/s^2","5 rad/s^2","10 rad/s^2","20 rad/s^2"],1,"The data imply I=2 kg m^2. Therefore alpha=tau/I=10/2=5 rad/s^2.",{stimulusGroupId:"pcm-set-u5",stimulus:PCM_SET_U5});

  const PCM_SET_U6 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"Four circular satellite orbits around the same planet are represented using radius and orbital speed relative to a reference circular orbit.", columns:["r/r0","v/v0"], rows:[[1,1],[4,0.5],[9,0.333],[16,0.25]] };
  p("pcm-set-u6-01","U6","6.6","Motion of Orbiting Satellites","3.C","Which dependence of orbital speed on radius is supported by the table?",["v proportional to r","v proportional to 1/r","v proportional to 1/sqrt(r)","v proportional to r^2"],2,"When radius is multiplied by 4, 9, and 16, speed is divided by 2, 3, and 4 respectively. This is the inverse-square-root relation v proportional to r^(-1/2).",{stimulusGroupId:"pcm-set-u6",stimulus:PCM_SET_U6});
  p("pcm-set-u6-02","U6","6.6","Motion of Orbiting Satellites","2.A","Which circular-orbit formula predicts the pattern?",["v=sqrt(GM/r)","v=GM/r","v=sqrt(GMr)","v=GM/r^2"],0,"Balancing gravitational and centripetal forces gives v=sqrt(GM/r), whose inverse-square-root radius dependence matches the normalized data.",{stimulusGroupId:"pcm-set-u6",stimulus:PCM_SET_U6});
  p("pcm-set-u6-03","U6","6.6","Motion of Orbiting Satellites","2.D","For a circular orbit at r=25r0, what normalized speed does the observed relationship predict?",["0.04v0","0.20v0","0.50v0","5v0"],1,"The speed ratio is 1/sqrt(25)=1/5=0.20, so the satellite would move at 0.20v0.",{stimulusGroupId:"pcm-set-u6",stimulus:PCM_SET_U6});

  const PCM_SET_U7 = { type:"table", source:"Original simulated data created for AP Exam Practice.", description:"A student attaches different masses to the same ideal spring and records the period of small horizontal oscillations for each mass.", columns:["m (kg)","T (s)"], rows:[[1,1],[4,2],[9,3],[16,4]] };
  p("pcm-set-u7-01","U7","7.2","Frequency and Period of SHM","3.C","Which dependence of period on mass is supported by the data?",["T proportional to m","T proportional to sqrt(m)","T proportional to 1/m","T is independent of m"],1,"Mass values 1, 4, 9, and 16 have square roots 1, 2, 3, and 4, exactly matching the measured periods, so T is proportional to sqrt(m).",{stimulusGroupId:"pcm-set-u7",stimulus:PCM_SET_U7});
  p("pcm-set-u7-02","U7","7.2","Frequency and Period of SHM","2.D","What period would the same trend predict for a 25 kg mass?",["2.5 s","5 s","6.25 s","25 s"],1,"The data follow T=sqrt(m) in the chosen units. For 25 kg, sqrt(25)=5, so the predicted period is 5 s.",{stimulusGroupId:"pcm-set-u7",stimulus:PCM_SET_U7});
  p("pcm-set-u7-03","U7","7.2","Frequency and Period of SHM","2.A","Which theoretical spring-mass relation is consistent with the measured mass dependence?",["T=2pi sqrt(m/k)","T=2pi sqrt(k/m)","T=2pi m/k","T=k/m"],0,"For a fixed spring constant k, T=2pi sqrt(m/k) predicts a period proportional to the square root of mass, matching the table.",{stimulusGroupId:"pcm-set-u7",stimulus:PCM_SET_U7});

'''
bp.write_text(b.replace(marker,block+marker,1))
