from pathlib import Path
import json
Q=[
("pcm-6.1-01","U6","6.1","Rotational Kinetic Energy","2.B","A wheel has rotational inertia 2 kg m^2 and angular speed 3 rad/s. What is its rotational kinetic energy?",["3 J","9 J","18 J","27 J"],1,"Rotational kinetic energy is K_rot=(1/2)I omega^2=(1/2)(2)(9)=9 J."),
("pcm-6.1-02","U6","6.1","Rotational Kinetic Energy","2.A","Which expression gives rotational kinetic energy of a rigid body about a fixed axis?",["I omega","(1/2)I omega^2","I alpha","(1/2)I alpha^2"],1,"The rotational analogue of translational kinetic energy is K_rot=(1/2)I omega^2 for a rigid body rotating about a fixed axis."),
("pcm-6.1-03","U6","6.1","Rotational Kinetic Energy","2.D","At fixed rotational inertia, angular speed triples. By what factor does rotational kinetic energy change?",["3","6","9","27"],2,"Because K_rot=(1/2)I omega^2, rotational kinetic energy scales with the square of angular speed. Tripling omega multiplies energy by nine."),
("pcm-6.2-01","U6","6.2","Torque and Work","2.B","A constant torque of 5 N m rotates a wheel through 4 radians in the torque's direction. How much work is done?",["1.25 J","9 J","20 J","100 J"],2,"For constant torque aligned with angular displacement, rotational work is W=tau Delta theta=(5)(4)=20 J."),
("pcm-6.2-02","U6","6.2","Torque and Work","2.A","For a torque tau(theta) about a fixed axis, which expression gives the work done between theta1 and theta2?",["integral tau dtheta","integral tau dt","tau(theta2)-tau(theta1)","integral theta dt"],0,"Rotational work is the angular analogue of integral F dx: W=integral from theta1 to theta2 of tau(theta) dtheta."),
("pcm-6.2-03","U6","6.2","Torque and Work","3.B","A net torque does positive work on a rigid rotor. What can be concluded about its rotational kinetic energy?",["It decreases","It increases by the net rotational work","It remains constant","It becomes zero"],1,"The rotational work-energy theorem states W_net=Delta K_rot. Positive net work therefore increases rotational kinetic energy by that amount."),
("pcm-6.3-01","U6","6.3","Angular Momentum and Angular Impulse","2.B","A rigid body has I=3 kg m^2 and omega=4 rad/s about a fixed principal axis. What is its angular momentum magnitude?",["0.75 kg m^2/s","7 kg m^2/s","12 kg m^2/s","24 kg m^2/s"],2,"For rotation about a fixed principal axis, angular momentum magnitude is L=I omega=(3)(4)=12 kg m^2/s."),
("pcm-6.3-02","U6","6.3","Angular Momentum and Angular Impulse","2.A","Which expression gives angular impulse about an axis over a time interval?",["integral tau dt","integral L dt","integral F dx","tau/Delta t"],0,"Angular impulse is the time integral of net torque and equals the change in angular momentum: Delta L=integral tau_net dt."),
("pcm-6.3-03","U6","6.3","Angular Momentum and Angular Impulse","2.C","Two particles have equal momentum magnitude p and move perpendicular to position vectors of lengths r and 2r. How do their angular momenta compare?",["They are equal","The 2r particle has twice the angular momentum","The 2r particle has four times the angular momentum","The r particle has twice the angular momentum"],1,"For perpendicular r and p, angular momentum magnitude is L=rp. Doubling r at fixed p doubles L."),
("pcm-6.4-01","U6","6.4","Conservation of Angular Momentum","3.B","When is a system's angular momentum about a chosen origin conserved?",["When net external torque about that origin is zero","Whenever linear momentum is zero","Only when kinetic energy is constant","Only for circular motion"],0,"Angular momentum changes according to the net external torque. If external torque about the chosen origin is zero, total angular momentum is conserved."),
("pcm-6.4-02","U6","6.4","Conservation of Angular Momentum","2.B","A skater reduces rotational inertia from 6 to 2 kg m^2 with negligible external torque. If initial angular speed is 2 rad/s, what is final angular speed?",["1 rad/s","2 rad/s","6 rad/s","12 rad/s"],2,"Conservation of angular momentum gives I_i omega_i=I_f omega_f. Thus (6)(2)=(2)omega_f, so omega_f=6 rad/s."),
("pcm-6.4-03","U6","6.4","Conservation of Angular Momentum","2.D","With negligible external torque, a rotating system's rotational inertia is halved. By what factor does angular speed change?",["It halves","It doubles","It quadruples","It is unchanged"],1,"Angular momentum L=I omega remains constant. Halving I therefore requires omega to double."),
("pcm-6.5-01","U6","6.5","Rolling","2.B","A solid disk rolls without slipping with center-of-mass speed 6 m/s and radius 2 m. What is its angular speed?",["3 rad/s","6 rad/s","12 rad/s","0.33 rad/s"],0,"For rolling without slipping, v_cm=omega R. Therefore omega=6/2=3 rad/s."),
("pcm-6.5-02","U6","6.5","Rolling","2.A","Which expression gives the total kinetic energy of a rigid body rolling without slipping?",["(1/2)Mv_cm^2 only","(1/2)I_cm omega^2 only","(1/2)Mv_cm^2+(1/2)I_cm omega^2","Mv_cm omega"],2,"Rolling combines translation of the center of mass with rotation about the center of mass, so total kinetic energy is the sum of both contributions."),
("pcm-6.5-03","U6","6.5","Rolling","3.C","Two objects of equal mass and radius roll without slipping down the same incline. The one with smaller I/(MR^2) arrives first. Why?",["More gravitational energy goes into translation for the smaller rotational inertia ratio","The smaller ratio eliminates gravity","Static friction necessarily does positive work","Mass conservation requires a higher speed"],0,"Both lose the same gravitational potential energy, but the object with smaller rotational inertia needs less rotational energy at a given speed, leaving more for translation."),
("pcm-6.6-01","U6","6.6","Motion of Orbiting Satellites","2.B","A satellite in a circular orbit of radius r around mass M has speed v. Which expression is correct?",["v=sqrt(GM/r)","v=GM/r^2","v=sqrt(GMr)","v=2pi r/GM"],0,"Equating gravitational force GMm/r^2 with centripetal force mv^2/r gives v=sqrt(GM/r)."),
("pcm-6.6-02","U6","6.6","Motion of Orbiting Satellites","2.A","Which expression gives total mechanical energy of mass m in a circular orbit of radius r around a much larger mass M?",["-GMm/(2r)","+GMm/(2r)","-GMm/r","0"],0,"For a circular orbit K=GMm/(2r) and U=-GMm/r, so E=K+U=-GMm/(2r)."),
("pcm-6.6-03","U6","6.6","Motion of Orbiting Satellites","2.D","A circular orbit radius increases by a factor of 4 around the same central mass. By what factor does orbital speed change?",["It doubles","It halves","It becomes one fourth","It is unchanged"],1,"Circular orbital speed scales as v proportional to r^(-1/2). Increasing radius by four reduces speed by sqrt(4)=2."),
("pcm-7.1-01","U7","7.1","Defining Simple Harmonic Motion (SHM)","3.B","Which force law produces ideal simple harmonic motion about x=0?",["F=+kx","F=-kx","F=-k/x^2","F=constant"],1,"Ideal SHM requires a restoring force proportional to displacement and opposite in direction, F=-kx."),
("pcm-7.1-02","U7","7.1","Defining Simple Harmonic Motion (SHM)","2.A","For a mass m attached to an ideal spring of constant k, which differential equation describes SHM?",["m x''+kx=0","m x''-kx=0","m x'+kx=0","m x''=k"],0,"Newton's second law with F=-kx gives m x''=-kx, or m x''+kx=0, the standard SHM equation."),
("pcm-7.1-03","U7","7.1","Defining Simple Harmonic Motion (SHM)","3.C","A measured acceleration-versus-position graph is a straight line through the origin with negative slope. Why does this support SHM?",["Acceleration is proportional to and opposite displacement","Velocity is constant","Energy is zero","Period must depend on amplitude"],0,"SHM requires a=-omega^2 x. A linear a-versus-x graph through the origin with negative slope directly matches that restoring-acceleration relation."),
("pcm-7.2-01","U7","7.2","Frequency and Period of SHM","2.B","A 1 kg mass oscillates on an ideal spring with k=4 N/m. What is the period?",["pi s","2pi s","pi/2 s","4pi s"],0,"The spring-mass period is T=2pi sqrt(m/k)=2pi sqrt(1/4)=pi s."),
("pcm-7.2-02","U7","7.2","Frequency and Period of SHM","2.A","Which expression gives the angular frequency of an ideal mass-spring oscillator?",["sqrt(k/m)","sqrt(m/k)","2pi sqrt(m/k)","k/m"],0,"Substituting x=A cos(omega t+phi) into m x''+kx=0 gives omega^2=k/m, so omega=sqrt(k/m)."),
("pcm-7.2-03","U7","7.2","Frequency and Period of SHM","2.D","The mass on an ideal spring is quadrupled while k is unchanged. How does the period change?",["It halves","It doubles","It quadruples","It is unchanged"],1,"Since T=2pi sqrt(m/k), quadrupling mass multiplies the period by sqrt(4)=2."),
("pcm-7.3-01","U7","7.3","Representing and Analyzing SHM","2.B","For x(t)=A cos(omega t), what is the velocity at the equilibrium position during a crossing?",["Zero","Maximum magnitude","Equal to A","Equal to omega only"],1,"At equilibrium x=0, kinetic energy and speed are maximal. Differentiating gives v=-A omega sin(omega t), whose magnitude is A omega there."),
("pcm-7.3-02","U7","7.3","Representing and Analyzing SHM","2.A","If x(t)=A cos(omega t+phi), which expression gives acceleration?",["-omega^2 x(t)","+omega^2 x(t)","-omega x(t)","A omega"],0,"Differentiating twice gives a(t)=-A omega^2 cos(omega t+phi)=-omega^2 x(t), the defining acceleration relation for SHM."),
("pcm-7.3-03","U7","7.3","Representing and Analyzing SHM","2.C","At positions x=A/2 and x=-A/2 in ideal SHM, how do speed magnitudes compare?",["Greater at +A/2","Greater at -A/2","They are equal","Both are zero"],2,"In ideal SHM speed depends on x^2 through v^2=omega^2(A^2-x^2), so positions of equal magnitude have equal speed magnitude."),
("pcm-7.4-01","U7","7.4","Energy of Simple Harmonic Oscillators","2.B","An ideal spring oscillator has amplitude A. What is its total mechanical energy?",["kA","(1/2)kA^2","kA^2","(1/2)mvA"],1,"At maximum displacement speed is zero and all energy is spring potential, so E=(1/2)kA^2."),
("pcm-7.4-02","U7","7.4","Energy of Simple Harmonic Oscillators","2.D","The amplitude of an ideal spring oscillator doubles. By what factor does total energy change?",["2","4","8","1/2"],1,"Total energy is E=(1/2)kA^2, so doubling amplitude multiplies the energy by four."),
("pcm-7.4-03","U7","7.4","Energy of Simple Harmonic Oscillators","3.B","Where is kinetic energy of an ideal spring oscillator greatest?",["At either turning point","At equilibrium","At maximum positive displacement only","It is constant everywhere"],1,"Potential energy is minimum at equilibrium, so with total energy conserved the kinetic energy and speed are greatest there."),
("pcm-7.5-01","U7","7.5","Simple and Physical Pendulums","2.B","For small oscillations, what is the period of a simple pendulum of length L?",["2pi sqrt(L/g)","2pi sqrt(g/L)","sqrt(Lg)","2pi L/g"],0,"For small angles, the pendulum equation linearizes to SHM with angular frequency sqrt(g/L), giving T=2pi sqrt(L/g)."),
("pcm-7.5-02","U7","7.5","Simple and Physical Pendulums","2.A","For a physical pendulum of mass M, pivot-to-center distance d, and rotational inertia I about the pivot, which small-angle period is correct?",["2pi sqrt(I/(Mgd))","2pi sqrt(Mgd/I)","2pi sqrt(Id/(Mg))","2pi I/(Mgd)"],0,"For small angles tau approximately -Mgd theta and I theta''=tau, so omega^2=Mgd/I and T=2pi sqrt(I/(Mgd))."),
("pcm-7.5-03","U7","7.5","Simple and Physical Pendulums","2.D","A simple pendulum's length is increased by a factor of 9 while g is unchanged. How does its small-angle period change?",["It triples","It increases ninefold","It decreases to one third","It is unchanged"],0,"Because T is proportional to sqrt(L), multiplying length by nine multiplies the period by sqrt(9)=3."),
]
bp=Path('data/ap-physics-c-mechanics.js'); b=bp.read_text(); marker='  window.QUESTIONS_AP_PHYSICS_C_MECHANICS = QUESTIONS;\n'
if marker not in b: raise SystemExit('bank export marker not found')
lines=[]
for q in Q: lines.append('  p('+','.join(json.dumps(x,ensure_ascii=False) for x in q)+');')
bp.write_text(b.replace(marker,'\n  // Units 6-7 — Rotating Systems and Oscillations\n'+'\n'.join(lines)+'\n\n'+marker,1))
