from pathlib import Path
import json
Q=[
("pcm-5.1-01","U5","5.1","Rotational Kinematics","2.B","A wheel starts from rest with constant angular acceleration 3 rad/s^2 for 4 s. What angular speed does it reach?",["3 rad/s","7 rad/s","12 rad/s","24 rad/s"],2,"For constant angular acceleration, omega=omega0+alpha t. Starting from rest gives omega=(3)(4)=12 rad/s."),
("pcm-5.1-02","U5","5.1","Rotational Kinematics","2.A","A rigid body's angular position is theta(t)=2t^3-t^2. Which expression gives its angular acceleration?",["6t^2-2t","12t-2","6t-2","12t"],1,"Angular velocity is dtheta/dt=6t^2-2t, and differentiating again gives angular acceleration alpha=12t-2."),
("pcm-5.1-03","U5","5.1","Rotational Kinematics","2.D","For constant angular acceleration from rest, the elapsed time doubles. By what factor does angular displacement change?",["2","4","8","1/2"],1,"From rest with constant angular acceleration, Delta theta=(1/2)alpha t^2. Doubling time multiplies angular displacement by four."),
("pcm-5.2-01","U5","5.2","Connecting Linear and Rotational Motion","2.B","A point on the rim of a wheel of radius 0.50 m rotates at 8 rad/s. What is its tangential speed?",["4 m/s","8 m/s","16 m/s","0.0625 m/s"],0,"Tangential speed and angular speed satisfy v=omega r. Multiplying 8 rad/s by 0.50 m gives 4 m/s."),
("pcm-5.2-02","U5","5.2","Connecting Linear and Rotational Motion","2.A","Which relation connects tangential acceleration a_t to angular acceleration alpha for a point a distance r from the axis?",["a_t=alpha/r","a_t=alpha r","a_t=alpha r^2","a_t=omega^2 r"],1,"Tangential acceleration is the rate of change of tangential speed v=omega r, so a_t=alpha r for fixed radius."),
("pcm-5.2-03","U5","5.2","Connecting Linear and Rotational Motion","2.C","Two points lie at radii r and 2r on the same rigid disk. How do angular and tangential speeds compare?",["Both are equal","Angular speeds equal; outer tangential speed is twice as large","Outer angular speed is twice as large; tangential speeds equal","Both outer quantities are twice as large"],1,"All points on a rigid body share the same angular speed, while tangential speed v=omega r is proportional to radius."),
("pcm-5.3-01","U5","5.3","Torque","2.B","A 20 N force is applied perpendicular to a 0.30 m wrench at its end. What torque magnitude is produced about the bolt?",["6 N m","20 N m","60 N m","0.015 N m"],0,"Torque magnitude is tau=rF sin phi. With a perpendicular force, sin phi=1, so tau=(0.30)(20)=6 N m."),
("pcm-5.3-02","U5","5.3","Torque","2.A","Which expression gives the vector torque of a force F applied at position vector r from an origin?",["r dot F","r cross F","F/r","rF^2"],1,"Torque is defined by the cross product tau=r cross F, which captures both the lever arm and rotational direction."),
("pcm-5.3-03","U5","5.3","Torque","2.D","The same perpendicular force is applied twice as far from a rotation axis. How does torque magnitude change?",["It halves","It doubles","It quadruples","It is unchanged"],1,"For a perpendicular force tau=rF. Holding F fixed while doubling the lever arm r doubles the torque magnitude."),
("pcm-5.4-01","U5","5.4","Rotational Inertia","2.B","Two point masses m are each located a distance r from an axis. What is their total rotational inertia?",["mr^2","2mr^2","2mr","m/r^2"],1,"For point masses I=sum m_i r_i^2. Two identical masses at radius r contribute mr^2 each, giving 2mr^2."),
("pcm-5.4-02","U5","5.4","Rotational Inertia","2.A","For a continuous mass distribution, which expression defines rotational inertia about a specified axis?",["integral r dm","integral r^2 dm","integral dm/r","integral v^2 dm"],1,"Rotational inertia weights each mass element by the square of its perpendicular distance from the axis: I=integral r^2 dm."),
("pcm-5.4-03","U5","5.4","Rotational Inertia","2.C","Two bodies have equal mass and outer radius. One has more mass concentrated near the axis. Which has smaller rotational inertia?",["The one with mass nearer the axis","The one with mass farther from the axis","They must be equal","The answer depends only on angular speed"],0,"Because each contribution scales as r^2 dm, concentrating more mass close to the axis reduces rotational inertia compared with placing it farther out."),
("pcm-5.5-01","U5","5.5","Rotational Equilibrium and Newton's First Law in Rotational Form","3.B","A rigid body is in static equilibrium. Which condition must hold about torque around any axis?",["Net torque is zero","Every individual torque is zero","Clockwise torque must be absent","Net force may be nonzero"],0,"Static equilibrium requires zero angular acceleration, so the vector sum of torques about any axis is zero; individual torques need not vanish."),
("pcm-5.5-02","U5","5.5","Rotational Equilibrium and Newton's First Law in Rotational Form","2.B","A 10 N downward force acts 2 m to the right of a pivot. What counterclockwise torque is needed for rotational equilibrium?",["5 N m","10 N m","20 N m","40 N m"],2,"The force produces a clockwise torque of magnitude rF=(2)(10)=20 N m, so equilibrium requires an equal 20 N m counterclockwise torque."),
("pcm-5.5-03","U5","5.5","Rotational Equilibrium and Newton's First Law in Rotational Form","3.C","A beam has zero net force but a nonzero net torque. Which motion is consistent with these conditions?",["No acceleration of any kind","Translational acceleration without angular acceleration","Angular acceleration without center-of-mass acceleration","Constant angular velocity only"],2,"Zero net force makes the center-of-mass acceleration zero, but nonzero net torque produces angular acceleration about the center of mass."),
("pcm-5.6-01","U5","5.6","Newton's Second Law in Rotational Form","2.B","A rigid body with rotational inertia 4 kg m^2 experiences net torque 12 N m. What is its angular acceleration?",["3 rad/s^2","8 rad/s^2","16 rad/s^2","48 rad/s^2"],0,"Rotational Newton's second law gives tau_net=I alpha. Thus alpha=12/4=3 rad/s^2."),
("pcm-5.6-02","U5","5.6","Newton's Second Law in Rotational Form","2.A","For rotation about a fixed axis with constant rotational inertia I, which relation is analogous to F=ma?",["tau=I alpha","tau=I omega","tau=alpha/I","tau=I theta"],0,"For a rigid body about a fixed axis, net torque equals rotational inertia times angular acceleration: tau_net=I alpha."),
("pcm-5.6-03","U5","5.6","Newton's Second Law in Rotational Form","2.D","The same net torque is applied to bodies with rotational inertias I and 2I. How do their angular accelerations compare?",["The 2I body has twice the angular acceleration","They are equal","The 2I body has half the angular acceleration","The 2I body has four times the angular acceleration"],2,"Since alpha=tau/I, doubling rotational inertia at fixed torque halves the angular acceleration."),
]
bp=Path('data/ap-physics-c-mechanics.js'); b=bp.read_text(); marker='  window.QUESTIONS_AP_PHYSICS_C_MECHANICS = QUESTIONS;\n'
if marker not in b: raise SystemExit('bank export marker not found')
lines=[]
for q in Q: lines.append('  p('+','.join(json.dumps(x,ensure_ascii=False) for x in q)+');')
bp.write_text(b.replace(marker,'\n  // Unit 5 — Torque and Rotational Dynamics\n'+'\n'.join(lines)+'\n\n'+marker,1))
