from pathlib import Path
p=Path('data/ap-physics-c-em.js')
lines=p.read_text().splitlines()
repls={
'em-8.6-03':('add("em-8.6-03","U8","8.6","Gauss\'s Law","3.C","A student chooses a cubic Gaussian surface around a point charge at its center and says Gauss\'s law cannot be used because the field is not constant over each face. Which response is best?","Gauss\'s law still fixes total flux, although the cube does not make the field easy to extract from the integral","The cube gives zero net flux because equal-area opposite faces must contribute equal and opposite flux","Gauss\'s law can be used only when the field is constant and perpendicular everywhere on the chosen surface","Gauss\'s law is valid only for spherical, cylindrical, or planar Gaussian surfaces with high symmetry","Gauss\'s law applies to every closed surface, but symmetry is needed to pull E outside the flux integral; a cube therefore gives correct total flux without directly yielding a simple E value.");'),
'em-10.1-02':('add("em-10.1-02","U10","10.1","Electrostatics with Conductors","3.C","A charged conductor in electrostatic equilibrium has excess charge on its surface. Which reasoning best justifies this result?","Excess charge in the conducting bulk would create an internal field that drives charge until equilibrium is restored","Mobile excess charge is pulled toward the exterior because gravity acts more strongly near the conducting surface","The conductor\'s interior cannot have electric potential, so any excess charge must migrate to the boundary","Electrostatic equilibrium requires the electric field outside the conductor to vanish, forcing charge onto its surface","In electrostatic equilibrium the electric field within the conducting material is zero. Any uncompensated excess charge in the bulk would create an internal field and continue driving mobile charge, so excess charge settles on the surface.");'),
'em-11.6-02':('add("em-11.6-02","U11","11.6","Kirchhoff\'s Loop Rule","3.C","Why must the algebraic sum of potential changes around any closed steady-state circuit loop equal zero?","Returning to the starting point requires the electric potential to have the same value after one complete loop","Resistors consume electrical charge along a loop while the battery restores exactly the charge lost in those resistors","All circuit elements in a closed loop must have the same resistance so their individual voltage changes cancel","Branch currents uniquely determine electric potential independently of path, which requires the same current in every loop element","Electric potential is single-valued. After traversing a closed path and returning to the same point, the net change in potential must be zero, which is Kirchhoff\'s loop rule.");'),
'em-11.4-04':('add("em-11.4-04","U11","11.4","Electric Power","3.C","Two resistors R and 2R are connected in series. A student claims the smaller resistor dissipates more power because its resistance is lower. Which response is correct?","The 2R resistor dissipates twice as much power because both carry the same current and P=I²R","Power cannot be compared unless the individual voltage across each resistor is measured directly","The R resistor dissipates twice as much power because the same series voltage appears across each resistor and P=V²/R","The resistors dissipate equal power because series elements carry the same current regardless of resistance","Series resistors carry the same current. Since P=I²R for a resistor, doubling resistance at fixed current doubles the dissipated power, so the 2R resistor dissipates twice as much.");')
}
seen={k:0 for k in repls}
out=[]
for line in lines:
    done=False
    for qid,new in repls.items():
        if line.startswith(f'add("{qid}"'):
            out.append(new);seen[qid]+=1;done=True;break
    if not done: out.append(line)
if any(v!=1 for v in seen.values()): raise SystemExit('hardening counts '+repr(seen))
p.write_text('\n'.join(out)+'\n')
