const fs = require('node:fs');
const path = 'js/subjects.js';
let s = fs.readFileSync(path, 'utf8');
const marker = 'id: "ap-computer-science-a"';
const start = s.indexOf(marker);
if (start < 0) throw new Error('AP CSA subject marker not found');
const end = s.indexOf('dataVar: "QUESTIONS_AP_COMPUTER_SCIENCE_A"', start);
if (end < 0) throw new Error('AP CSA subject end marker not found');
const block = s.slice(start, end);
if (!block.includes('releaseStatus: "draft"')) throw new Error('AP CSA is not draft at promotion time');
const promoted = block.replace('releaseStatus: "draft"', 'releaseStatus: "released"');
s = s.slice(0, start) + promoted + s.slice(end);
fs.writeFileSync(path, s);
