from pathlib import Path
p=Path('tests/ap-physics-c-mechanics.test.js')
s=p.read_text()
s=s.replace('  const ids = new Set();\n  for (const q of bank) {','  const ids = new Set();\n  const shortRationales = [];\n  for (const q of bank) {',1)
s=s.replace('    assert.ok(q.e.length >= 70, `${q.id}: rationale is too short (${q.e.length})`);','    if (q.e.length < 90) shortRationales.push(`${q.id}:${q.e.length}`);',1)
s=s.replace('  }\n});\n\ntest("Mechanics bank has seven original three-question shared data sets"','  }\n  assert.deepEqual(shortRationales, [], `rationales below 90 characters: ${shortRationales.join(", ")}`);\n});\n\ntest("Mechanics bank has seven original three-question shared data sets"',1)
s=s.replace('test("Mechanics answer construction has no gross key-position or length tell", () => {','test("Mechanics answer construction meets project bias and distractor standards", () => {',1)
s=s.replace('  const keys=[0,0,0,0];\n  for (const q of bank) {','  const keys=[0,0,0,0];\n  const absoluteLanguage=/\\b(always|never|every|only|entirely|unlimited|impossible|guaranteed)\\b/i;\n  for (const q of bank) {',1)
s=s.replace('    keys[q.c[0]]++;\n  }','    keys[q.c[0]]++;\n    const absoluteDistractors=q.o.filter((_,i)=>i!==q.c[0]).filter((o)=>absoluteLanguage.test(o));\n    assert.ok(absoluteDistractors.length<=1, `${q.id}: stacked absolute-language distractors`);\n  }',1)
s=s.replace('<= 0.30','<= 0.25',1).replace('<= 0.62','<= 0.58',1).replace('<= 0.18','<= 0.12',1)
p.write_text(s)
