from pathlib import Path
p=Path('data/ap-comparative-government.js')
s=p.read_text()
marker='''  const countryFacts = {\n'''
evidence=r'''  // Topic-specific, stable country evidence used by the application and comparison
  // templates. These statements deliberately avoid current office-holder names and
  // volatile election results; they encode institutional/course knowledge from the
  // Fall-2026 CED rather than news-dependent facts.
  const topicEvidence = {
    "1.1":["Mexico's transition from long PRI dominance to competitive elections provides evidence that can be compared across time","The United Kingdom's parliamentary elections and confidence relationship provide observable institutional evidence","political scientists can compare observable institutions and outcomes without treating normative judgments as empirical findings"],
    "1.2":["Mexico is a sovereign federal state whose government operates through constitutionally defined institutions","The United Kingdom is a sovereign state governed through parliamentary institutions under an uncodified constitutional order","state sovereignty and the institutions exercising governmental authority are related but analytically distinct"],
    "1.3":["Mexico holds competitive multiparty elections in which opposition parties can win national office","China's Communist Party dominates political competition and restricts organized challenges to one-party rule","meaningful electoral competition separates democratic accountability from authoritarian political control"],
    "1.4":["Mexico's erosion of PRI electoral dominance expanded genuine competition and alternation in national office","Russia's political system has moved toward greater executive dominance and more constrained opposition competition","democratization can advance or recede as competition, civil liberties, and institutional constraints change"],
    "1.5":["Iran combines electoral institutions with religious authority vested in powerful unelected bodies","The United Kingdom derives governing authority from parliamentary institutions, elections, and constitutional conventions","different regimes legitimate authority through different combinations of elections, law, religion, ideology, and tradition"],
    "1.6":["Nigeria transfers presidential authority through constitutionally scheduled elections and succession rules","The United Kingdom can replace a prime minister through party leadership change or loss of parliamentary confidence","leadership turnover follows different institutional channels in presidential and parliamentary systems"],
    "1.7":["Nigeria constitutionally divides powers among federal, state, and local levels","The United Kingdom remains legally unitary even though substantial powers have been devolved to Scotland, Wales, and Northern Ireland","constitutional federalism differs from devolution because subnational authority has a different legal foundation"],
    "1.8":["China frequently grounds legitimacy in economic performance, nationalism, and Communist Party leadership","Mexico's competitive elections provide an important procedural source of governmental legitimacy","regimes can seek public acceptance through performance or electoral procedures even when their political systems differ"],
    "1.9":["China uses policy performance, nationalism, and party institutions to reinforce regime support","The United Kingdom uses competitive elections, parliamentary accountability, and policy responsiveness to renew governing mandates","regimes sustain legitimacy through different mixes of performance, institutions, and citizen input"],
    "1.10":["Russia's centralized executive authority can reduce open elite competition while creating dependence on regime performance","Nigeria's regional, ethnic, and religious cleavages place continuing demands on federal institutions","political stability depends on how institutions manage legitimacy, cleavages, elite competition, and economic pressures"],
    "2.1":["The United Kingdom's prime minister and cabinet emerge from and remain responsible to Parliament","Mexico separately elects a president and a legislature for fixed terms","parliamentary fusion and presidential separation create different executive-legislative accountability relationships"],
    "2.2":["The United Kingdom can remove a government through parliamentary confidence mechanisms","Russia combines a directly elected president with a prime minister and government responsible within a semi-presidential structure","executive-legislative bargaining differs when authority is fused, separated, or divided between two executive offices"],
    "2.3":["Russia's presidency possesses extensive formal and informal influence over national policymaking","The United Kingdom's prime minister depends on maintaining support within the parliamentary majority","executive power depends not only on formal authority but also on party, legislative, and institutional relationships"],
    "2.4":["Mexico constitutionally limits presidents to a single six-year term without reelection","Russia has altered presidential term rules in ways that allow extended tenure in the presidency","term-limit design changes opportunities for leadership turnover and executive entrenchment"],
    "2.5":["A United Kingdom government can fall after losing parliamentary confidence or governing-party support","Nigeria's president serves a fixed term and can be removed through constitutional impeachment procedures","removal mechanisms reflect the different accountability structures of parliamentary and presidential systems"],
    "2.6":["Nigeria's bicameral National Assembly represents citizens through a House and states through a Senate","China's National People's Congress formally legislates but operates within Communist Party political dominance","legislative structure and political independence jointly determine how effectively legislatures represent interests and constrain executives"],
    "2.7":["The United Kingdom Parliament can question ministers, scrutinize bills, investigate government, and withdraw confidence","China's legislature operates within a party-state system that sharply limits autonomous opposition to top leadership","legislative checks are stronger when representatives possess institutional autonomy from the executive or ruling party"],
    "2.8":["United Kingdom courts apply statutes and common law within a system where Parliament remains legally sovereign","Iran's judiciary operates within an Islamic constitutional system influenced by unelected religious institutions","judicial roles vary with constitutional structure and the relationship between courts and other political authorities"],
    "2.9":["United Kingdom judges have substantial security and professional autonomy even though courts cannot invalidate Acts of Parliament","China's courts remain institutionally subordinate to Communist Party political authority","judicial independence concerns freedom from political control and is distinct from the formal scope of judicial review"],
    "3.1":["United Kingdom civil society organizations can openly organize, lobby, campaign, and criticize public officials","China permits many social organizations while restricting autonomous groups viewed as threats to party control","civil society's political influence depends heavily on legal protections and the state's tolerance for independent organization"],
    "3.2":["Iran's political culture reflects influences from Shi'a religious traditions, nationalism, revolution, and generational change","The United Kingdom's political culture includes long-standing acceptance of parliamentary institutions and gradual constitutional change","political culture shapes how citizens interpret authority and institutions but can contain competing traditions within one country"],
    "3.3":["China's ruling party officially draws on Marxism-Leninism while combining it with nationalism and state-led development","United Kingdom parties compete over market policy, welfare provision, national identity, and the appropriate scope of government","ideologies organize political beliefs differently across authoritarian and competitive party systems"],
    "3.4":["Iranian political values are shaped by religion, revolutionary institutions, education, media, family, and generational experience","Mexican political values have been shaped by democratization, regional experience, parties, media, and socioeconomic change","political socialization occurs through multiple institutions and can produce generational or regional differences within a country"],
    "3.5":["Mexico provides electoral, party, protest, interest-group, and civic channels for political participation","China permits selected forms of participation while constraining organized opposition and unauthorized collective action","regime openness changes which forms of participation are available and how much influence they can exert"],
    "3.6":["Russia permits voting and some civic activity while legal and political constraints raise the costs of opposition mobilization","United Kingdom citizens can use elections, parties, petitions, protests, interest groups, and direct contact with representatives","civil liberties, efficacy, institutions, resources, and repression shape both the level and form of participation"],
    "3.7":["United Kingdom law provides broad protections for expression, association, due process, and equal treatment","Iran constitutionally recognizes some rights while religious and political restrictions limit expression, association, and personal autonomy","formal rights protections can differ from actual enforcement, especially where unelected authorities or security institutions constrain liberties"],
    "3.8":["Nigeria's regional, ethnic, religious, and socioeconomic cleavages shape parties, federal bargaining, and public policy","United Kingdom politics includes regional and national-identity cleavages alongside class and partisan divisions","social cleavages become politically important when institutions and parties organize or respond to those identities"],
    "3.9":["Nigeria's federal arrangements and informal power-sharing practices seek to manage reinforcing regional and religious cleavages","Russia's center-periphery and ethnic diversity is managed within an increasingly centralized federal system","institutions can reduce or intensify conflict depending on whether they accommodate, cross-cut, or suppress politically salient cleavages"],
    "4.1":["The United Kingdom elects the House of Commons primarily through single-member plurality districts","Mexico combines single-member districts with proportional representation in elections to the Chamber of Deputies","electoral formulas shape incentives for parties, geographic accountability, and the proportionality of representation"],
    "4.2":["Mexico's mixed electoral rules balance district representation with broader proportional inclusion","Iran screens candidates through unelected institutions before voters choose among approved contenders","election rules can promote representation or governability while also structuring who can compete for office"],
    "4.3":["China operates a Communist Party-dominated party-state rather than a competitive multiparty system","The United Kingdom has competitive national parties and a party system shaped by plurality elections and regional parties","party-system competition varies with regime type, electoral rules, and social cleavages"],
    "4.4":["Mexico's parties recruit candidates, organize elections, aggregate interests, and compete to control elected institutions","China's Communist Party recruits political elites, sets major policy direction, and penetrates state and social institutions","parties link citizens and rulers differently in competitive electoral systems and dominant party-states"],
    "4.5":["Mexican social movements and interest groups use elections, litigation, protest, lobbying, and media to pressure government","Iranian social movements can mobilize around social and political grievances despite substantial restrictions and repression","organized groups can shape agendas and participation even when regimes offer very different levels of political access"],
    "4.6":["United Kingdom interest groups generally compete pluralistically for access to parties, Parliament, ministries, and public opinion","Mexico historically incorporated important labor and sectoral organizations through corporatist relationships tied to the PRI","pluralist competition differs from corporatist arrangements in how groups gain recognized access to policymakers"],
    "5.1":["China's integration into global trade and rapid technological development expanded growth while giving the state new tools for economic and information management","Nigeria's dependence on global commodity markets and expanding digital connectivity expose it to external price and technology shifts","global markets and technology can simultaneously expand economic opportunities and constrain or reshape state policy choices"],
    "5.2":["China combines market mechanisms and global trade with extensive state ownership, regulation, and industrial policy","The United Kingdom generally relies more heavily on private markets while using regulation, taxation, and social policy to respond to market outcomes","states respond to global market pressures with different mixtures of liberalization, regulation, ownership, and social protection"],
    "5.3":["Mexico's integration into North American production networks created export opportunities while exposing sectors and regions to uneven adjustment","United Kingdom debates over European integration reflected tensions involving sovereignty, migration, regulation, and economic interdependence","globalization creates uneven gains and losses that can generate political demands for both openness and protection"],
    "5.4":["Mexico pursued privatization, trade opening, and other market-oriented reforms after an earlier period of stronger state economic control","China introduced market-oriented reforms while retaining Communist Party rule and substantial state direction of strategic sectors","economic liberalization can reduce direct state control without necessarily producing equivalent political liberalization"],
    "5.5":["The United Kingdom participates in international organizations while its withdrawal from the European Union reduced direct supranational constraints from EU institutions","Russia participates in international organizations while emphasizing state sovereignty and resisting external constraints it views as threatening","international and supranational institutions differ in how much authority states delegate and how strongly rules constrain domestic policy"],
    "5.6":["Mexico has expanded and revised social programs in response to inequality, poverty, demographic change, and political competition","Nigeria faces pressure to expand education, health, employment, and social provision amid rapid population growth and uneven state capacity","social policy adaptation reflects demographic needs, fiscal capacity, development levels, and political demands"],
    "5.7":["China's industrialization produced rapid urbanization, rising incomes, pollution, regional inequality, and new social demands","Nigeria's development is shaped by urbanization and resource wealth alongside infrastructure gaps, unemployment, and regional inequality","economic development can expand resources and middle classes while also creating environmental, distributional, and governance pressures"],
    "5.8":["China faces population aging and a shrinking working-age population after decades of low fertility","Nigeria has a much younger and faster-growing population that creates strong demand for education, employment, housing, and services","different demographic structures create contrasting fiscal, labor-market, and service-delivery pressures on governments"],
  };

'''
if marker not in s: raise SystemExit('countryFacts marker missing')
s=s.replace(marker,evidence+marker,1)
old_b='''    bank.push(make(`compgov-${code}-b`,t,"1.E",`A researcher examining ${a} wants to apply the central idea of ${name}. Which observation is most relevant?`,`${countryFacts[a]}; this provides a country context in which to apply ${name.toLowerCase()}.`,[
      `${countryFacts[b]}; this describes ${b} rather than the country in the prompt.`,
      `${countryFacts[countries[(countries.indexOf(a)+2)%countries.length]]}; this shifts the analysis to a different course country.`,
      `${countryFacts[countries[(countries.indexOf(a)+3)%countries.length]]}; this is not evidence about ${a}.`
    ],`The correct response applies the topic to ${a}: ${countryFacts[a]}. The alternatives describe other course countries and therefore do not answer the country-specific application.`,vg1));'''
new_b='''    const ev = topicEvidence[code];
    if (!ev) throw new Error(`${code}: missing topic-specific comparative evidence`);
    const sameUnitEvidence = peers.map(x => topicEvidence[x[0]] && topicEvidence[x[0]][0]).filter(Boolean);
    bank.push(make(`compgov-${code}-b`,t,"1.E",`Which piece of evidence from ${a} most directly illustrates ${name}?`,ev[0],sameUnitEvidence,`The evidence is directly tied to ${name}: ${ev[0]}. The competing statements describe other political processes from the same unit rather than the concept named in the prompt.`,vg1));'''
if old_b not in s: raise SystemExit('b template missing')
s=s.replace(old_b,new_b)
old_c='''    bank.push(make(`compgov-${code}-c`,t,"1.B",`Which explanation best connects ${name} to political outcomes?`,`${principle} As a result, variation in this feature can change incentives, participation, accountability, legitimacy, or policy outcomes.`,peers.map(x=>`${x[3]} As a result, the mechanism in Topic ${x[0]} is the primary explanation here.`),`${principle} The political effect follows from how that institution or process changes incentives and relationships among citizens, officials, and the state.`,vg1));'''
new_c='''    bank.push(make(`compgov-${code}-c`,t,"1.B",`Which explanation best connects ${name} to political outcomes?`,`${principle} This can alter the incentives and relationships among citizens, political organizations, officials, and the state.`,peers.map(x=>`${x[3]} This instead emphasizes the mechanism associated with ${x[2]}, not the process named in the prompt.`),`${principle} The mechanism matters because it changes the incentives or relationships through which political actors pursue authority, participation, accountability, or policy.`,vg1));'''
if old_c not in s: raise SystemExit('c template missing')
s=s.replace(old_c,new_c)
old_d='''    bank.push(make(`compgov-${code}-d`,t,"2.A",`Which comparison between ${a} and ${b} is most accurate for the issues raised by ${name}?`,`${a}: ${countryFacts[a]}; ${b}: ${countryFacts[b]}.`,countries.filter(c=>c!==a&&c!==b).slice(0,3).map((c,i)=>`${a}: ${countryFacts[c]}; ${b}: ${countryFacts[i%2===0?a:b]}.`),`The defensible comparison uses the actual institutional context of both countries: ${a}—${countryFacts[a]}; ${b}—${countryFacts[b]}.`,vg2));'''
new_d='''    const peerEvidence = peers.map(x => topicEvidence[x[0]]).filter(Boolean);
    bank.push(make(`compgov-${code}-d`,t,"2.A",`Which comparison between ${a} and ${b} is most accurate for ${name}?`,`${a}: ${ev[0]} ${b}: ${ev[1]}`,peerEvidence.map(x=>`${a}: ${x[0]} ${b}: ${x[1]}`),`The correct comparison uses topic-specific evidence from both cases. ${a}: ${ev[0]} ${b}: ${ev[1]}`,vg2));'''
if old_d not in s: raise SystemExit('d template missing')
s=s.replace(old_d,new_d)
old_e='''    bank.push(make(`compgov-${code}-e`,t,"2.C",`What is the most defensible implication of a difference between ${a} and ${b} when analyzing ${name}?`,`${a} and ${b} operate through different institutional and political contexts, so the same political pressure can produce different channels of accountability, participation, or policy response.`,[
      `Because both are sovereign states, institutional differences rarely affect how political pressures are translated into policy.`,
      `A difference in political institutions means citizens in one country cannot participate politically while citizens in the other always can.`,
      `The comparison shows that economic development alone determines the political institutions and behaviors of both countries.`
    ],`Comparative analysis asks what institutional similarities or differences imply. Different structures can mediate the same pressure differently without making absolute claims about participation or reducing politics to one cause.`,vg2));'''
new_e='''    bank.push(make(`compgov-${code}-e`,t,"2.C",`What is the most defensible implication of the comparison between ${a} and ${b} for ${name}?`,ev[2],peerEvidence.map(x=>x[2]),`The comparison supports this topic-specific implication: ${ev[2]}. The alternatives draw implications from different processes in the same unit rather than from the evidence in this comparison.`,vg2));'''
if old_e not in s: raise SystemExit('e template missing')
s=s.replace(old_e,new_e)
p.write_text(s)
