from pathlib import Path
p=Path('data/ap-biology.js')
s=p.read_text()
repls=[
('q("U5", "5.4", "Non-Mendelian Genetics", "5.A", "A mother carries an X-linked recessive allele and the father lacks it. What fraction of their sons is expected to express the trait?", "One-half", ["None", "One-fourth", "All"]);',
 'q("U5", "5.4", "Non-Mendelian Genetics", "5.A", "A mother carries an X-linked recessive allele and the father lacks it. What fraction of their sons is expected to express the trait?", "One-half", ["One-eighth", "One-fourth", "Three-fourths"]);'),
('q("U7", "7.10", "Speciation", "1.B", "Allopatric speciation commonly begins when", "geographic separation reduces gene flow between populations", ["individuals within one population mate completely at random", "natural selection eliminates all genetic variation", "two species fuse into one shared gene pool"]);',
 'q("U7", "7.10", "Speciation", "1.B", "Allopatric speciation commonly begins when", "geographic separation reduces gene flow between populations", ["mating remains unrestricted throughout one continuous population", "selection reduces variation while gene flow between populations remains high", "previously separated populations merge into one freely interbreeding population"]);'),
('q("U6", "6.7", "Mutations", "3.B", "A mutation changes a codon but not the encoded amino acid. The most likely explanation is that", "multiple codons can specify the same amino acid", ["ribosomes translate DNA without reading codons", "every mutation is removed before transcription", "amino acids determine the nucleotide sequence of mRNA"]);',
 'q("U6", "6.7", "Mutations", "3.B", "A student predicts that a single-base substitution can change an mRNA codon without changing the encoded amino acid. Which result would support the prediction?", "The original and substituted codons differ in sequence but specify the same amino acid.", ["The substituted codon causes the ribosome to stop before reaching it.", "The DNA substitution is removed before the gene is transcribed.", "The substituted codon changes the amino acid and every downstream codon."]);'),
('q("U5", "5.3", "Mendelian Genetics", "6.B", "A testcross is useful for determining the genotype of an individual with a dominant phenotype because the individual is crossed with", "a homozygous recessive partner whose gametes reveal the unknown alleles", ["a homozygous dominant partner that contributes the dominant allele to each offspring", "a heterozygous partner that produces both allele types in equal proportions", "a partner with the same phenotype whose genotype is also unknown"]);',
 'q("U5", "5.3", "Mendelian Genetics", "6.B", "An individual with a dominant phenotype is crossed with a homozygous recessive tester, and both dominant- and recessive-phenotype offspring are produced. Which claim is best supported by this evidence?", "The unknown parent is heterozygous because production of recessive offspring shows that it contributed a recessive allele.", ["The unknown parent is homozygous dominant because dominant offspring were produced.", "The tester must be heterozygous because two offspring phenotypes occurred.", "The offspring data cannot provide evidence about the unknown parent's genotype."]);'),
('q("U8", "8.6", "Biodiversity", "6.B", "Why can greater genetic diversity increase a population\'s persistence during environmental change?", "Some individuals may carry alleles that confer survival under the new conditions.", ["A diverse population uses fewer resources because its individuals share a niche.", "Greater diversity reduces the chance that beneficial alleles are inherited.", "Genetic diversity keeps abiotic conditions constant around the population."]);',
 'q("U8", "8.6", "Biodiversity", "6.B", "After an abrupt environmental change, a genetically diverse population includes some individuals that survive and reproduce while several common genotypes decline. Which claim is best supported by this evidence?", "Genetic diversity can increase population persistence because some individuals may carry alleles that confer survival under the new conditions.", ["Genetic diversity prevents environmental conditions from changing around the population.", "A population persists only when all individuals use the same resources in the same way.", "The decline of common genotypes shows that heritable variation cannot affect survival."]);'),
('q("U5", "5.4", "Non-Mendelian Genetics", "6.C", "A single gene has three alleles in a population, and two alleles are codominant in heterozygotes. Which claim follows?", "The population can contain more than two alleles even though each diploid individual carries only two.", ["Each individual carries all three alleles in every somatic cell.", "Codominance prevents alleles from segregating during meiosis.", "The heterozygote phenotype establishes that the gene is polygenic."]);',
 'q("U5", "5.4", "Non-Mendelian Genetics", "6.C", "A single gene has three alleles in a population, although each diploid individual carries only two copies of the gene. Which reasoning best justifies how both statements can be true?", "Allele number is a population-level property, while each diploid individual inherits only one allele on each of two homologous chromosomes.", ["Each individual temporarily carries all population alleles and deletes one before reproduction.", "Codominance prevents alleles from segregating, so extra alleles remain outside chromosomes.", "Having more than two population alleles means that the trait must be controlled by several genes."]);'),
('q("U7", "7.2", "Natural Selection", "6.C", "A drought leaves mostly hard seeds, and birds with deeper beaks produce more surviving offspring. Which prediction follows?", "Alleles associated with deeper beaks may increase in frequency in later generations.", ["Individual birds will deepen their beaks during life and transmit the change.", "Seed hardness will cause the same beak mutation in each offspring.", "Beak-depth variation will disappear before reproductive success differs."]);',
 'q("U7", "7.2", "Natural Selection", "6.C", "A drought leaves mostly hard seeds, and birds with deeper beaks produce more surviving offspring. Which reasoning best connects these observations to a change in the population over generations?", "If beak depth is heritable, deeper-beaked birds contribute more copies of associated alleles, so those alleles may increase in frequency.", ["Individual birds deepen their beaks during life and then transmit the acquired change.", "Hard seeds induce the same beneficial beak mutation in each bird before reproduction.", "Differential reproductive success removes heritable beak-depth variation before allele frequencies can change."]);'),
('q("U8", "8.4", "Effect of Density on Populations", "6.C", "Two populations experience the same drought, but the denser population also has much higher disease transmission. Which claim is best supported?", "Drought is density independent, while disease transmission is density dependent.", ["Both factors are density dependent because both reduce population size.", "Drought is density dependent, while disease transmission is density independent.", "Neither factor can affect carrying capacity or population growth."]);',
 'q("U8", "8.4", "Effect of Density on Populations", "6.C", "Two populations experience the same drought, but the denser population also has much higher disease transmission. Which reasoning best explains why the two factors differ in density dependence?", "Drought exposure does not require crowding, whereas higher density increases contact opportunities that can raise disease transmission.", ["Any factor that reduces population size is density dependent, so drought and disease are equivalent.", "Drought becomes stronger as population density rises, whereas transmission falls as contacts become more frequent.", "Density dependence can be determined only from whether a factor changes carrying capacity, not from how its effect varies with density."]);')
]
for old,new in repls:
    if old not in s: raise SystemExit('missing replacement target: '+old[:100])
    s=s.replace(old,new,1)
exp_repls=[
('"apbio-u5-006": "A homozygous recessive tester contributes only recessive alleles, so offspring phenotypes reveal which allele came from the unknown parent. Dominant or heterozygous testers obscure that inference.",',
 '"apbio-u5-006": "A homozygous recessive tester contributes only recessive alleles. Because recessive offspring occurred, the unknown dominant-phenotype parent must have contributed a recessive allele and therefore is heterozygous.",'),
('"apbio-u6-010": "A codon can change without changing its amino acid because the genetic code is redundant. Several amino acids are specified by more than one codon, often differing at the third base.",',
 '"apbio-u6-010": "The prediction is supported when the substituted and original codons have different nucleotide sequences yet specify the same amino acid. That outcome follows from redundancy of the genetic code and is a silent substitution.",'),
('"apbio-u5-019": "A population may contain many alleles at one locus even though a diploid individual can carry only two alleles at that locus. Codominance affects phenotype, not chromosome number or segregation.",',
 '"apbio-u5-019": "Allele diversity is counted across the population, whereas one diploid individual has only two homologous copies of the locus and therefore at most two alleles. This connects population-level diversity with individual inheritance.",'),
('"apbio-u7-017": "Deeper-beaked birds leave more surviving offspring under the drought conditions. If beak depth is heritable, alleles associated with deeper beaks can therefore become more common in later generations.",',
 '"apbio-u7-017": "The evidence shows differential reproductive success. If beak depth is heritable, deeper-beaked birds contribute more copies of associated alleles to the next generation, providing the reasoning that links survival to allele-frequency change.",'),
('"apbio-u8-006": "Genetic diversity increases the chance that at least some individuals possess alleles suited to a new condition. Those individuals can survive and reproduce, helping the population persist.",',
 '"apbio-u8-006": "The observed survival of some genotypes during environmental change supports the claim that genetic diversity can aid persistence. Heritable differences can leave some individuals better able to survive and reproduce under the new conditions.",'),
('"apbio-u8-019": "Drought acts regardless of how crowded the population is, whereas disease transmission often increases with contact rate and therefore population density. The comparison separates density-independent and density-dependent effects.",',
 '"apbio-u8-019": "Drought can affect individuals regardless of crowding, whereas denser populations create more contact opportunities for pathogen transmission. That mechanism connects the observations to the distinction between density-independent and density-dependent factors.",')
]
for old,new in exp_repls:
    if old not in s: raise SystemExit('missing explanation target: '+old[:80])
    s=s.replace(old,new,1)
p.write_text(s)
Path('tests/ap-biology-naive-audit-regressions.test.js').write_text('''const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs"),vm=require("node:vm");const sb={window:{}};vm.createContext(sb);vm.runInContext(fs.readFileSync("data/ap-biology.js","utf8"),sb);const byId=new Map(sb.window.QUESTIONS_AP_BIOLOGY.map(q=>[q.id,q]));
test("Biology audit-flagged distractors are competitive rather than stacked absolutes",()=>{const abs=/\\b(always|never|every|entirely|completely|impossible|guarantee[sd]?|automatically|all|none|identical|unlimited)\\b/i;for(const id of ["apbio-u5-008","apbio-u7-010"]){const q=byId.get(id);assert.ok(q.o.filter((o,i)=>i!==q.c[0]&&abs.test(o)).length<2,id)}});
test("Biology exact science-practice repairs assess their declared task",()=>{assert.match(byId.get("apbio-u6-010").q,/predicts/i);assert.match(byId.get("apbio-u6-010").q,/result would support/i);assert.match(byId.get("apbio-u5-006").q,/claim is best supported/i);assert.match(byId.get("apbio-u8-006").q,/claim is best supported/i);for(const id of ["apbio-u5-019","apbio-u7-017","apbio-u8-019"])assert.match(byId.get(id).q,/reasoning/i,id)});
''')