name: Verify EM Release Artifact
on:
  push:
    branches: [integration/ap-physics-c-em-release]
    paths:
      - '.github/workflows/_verify_em_release_artifact.yml'
permissions:
  contents: read
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run check
      - uses: actions/upload-artifact@v4
        with:
          name: em-release-site
          path: _site
          if-no-files-found: error
